//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MobLink.Framework.WebServices._WSPatioxDetran {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSPatioxDetranSoap", Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(object[]))]
    public partial class WSPatioxDetran : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback InclusaoVeiculoPatioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarVeiculosPatioOperationCompleted;
        
        private System.Threading.SendOrPostCallback LiberarVeiculoPatioOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarVistoriaOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarExtratoLeilaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarPendenciasLiberacaoVeiculoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarVeiculoParaLeilaoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarCodigosMunicipiosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarVeiculoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ConsultarVeiculoClasseOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSPatioxDetran() {
            this.Url = global::MobLink.Framework.WebServices.Properties.Settings.Default.MobLink_Framework_WebServices_WSPatioxDetran_WSPatioxDetran;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event InclusaoVeiculoPatioCompletedEventHandler InclusaoVeiculoPatioCompleted;
        
        /// <remarks/>
        public event ConsultarVeiculosPatioCompletedEventHandler ConsultarVeiculosPatioCompleted;
        
        /// <remarks/>
        public event LiberarVeiculoPatioCompletedEventHandler LiberarVeiculoPatioCompleted;
        
        /// <remarks/>
        public event CadastrarVistoriaCompletedEventHandler CadastrarVistoriaCompleted;
        
        /// <remarks/>
        public event CadastrarExtratoLeilaoCompletedEventHandler CadastrarExtratoLeilaoCompleted;
        
        /// <remarks/>
        public event ConsultarPendenciasLiberacaoVeiculoCompletedEventHandler ConsultarPendenciasLiberacaoVeiculoCompleted;
        
        /// <remarks/>
        public event ConsultarVeiculoParaLeilaoCompletedEventHandler ConsultarVeiculoParaLeilaoCompleted;
        
        /// <remarks/>
        public event ConsultarCodigosMunicipiosCompletedEventHandler ConsultarCodigosMunicipiosCompleted;
        
        /// <remarks/>
        public event ConsultarVeiculoCompletedEventHandler ConsultarVeiculoCompleted;
        
        /// <remarks/>
        public event ConsultarVeiculoClasseCompletedEventHandler ConsultarVeiculoClasseCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/InclusaoVeiculoPatio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string InclusaoVeiculoPatio(Veiculoinclusao veiculo) {
            object[] results = this.Invoke("InclusaoVeiculoPatio", new object[] {
                        veiculo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void InclusaoVeiculoPatioAsync(Veiculoinclusao veiculo) {
            this.InclusaoVeiculoPatioAsync(veiculo, null);
        }
        
        /// <remarks/>
        public void InclusaoVeiculoPatioAsync(Veiculoinclusao veiculo, object userState) {
            if ((this.InclusaoVeiculoPatioOperationCompleted == null)) {
                this.InclusaoVeiculoPatioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnInclusaoVeiculoPatioOperationCompleted);
            }
            this.InvokeAsync("InclusaoVeiculoPatio", new object[] {
                        veiculo}, this.InclusaoVeiculoPatioOperationCompleted, userState);
        }
        
        private void OnInclusaoVeiculoPatioOperationCompleted(object arg) {
            if ((this.InclusaoVeiculoPatioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.InclusaoVeiculoPatioCompleted(this, new InclusaoVeiculoPatioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarVeiculosPatio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarVeiculosPatio(VeiculoConsultaPatio veiculo) {
            object[] results = this.Invoke("ConsultarVeiculosPatio", new object[] {
                        veiculo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarVeiculosPatioAsync(VeiculoConsultaPatio veiculo) {
            this.ConsultarVeiculosPatioAsync(veiculo, null);
        }
        
        /// <remarks/>
        public void ConsultarVeiculosPatioAsync(VeiculoConsultaPatio veiculo, object userState) {
            if ((this.ConsultarVeiculosPatioOperationCompleted == null)) {
                this.ConsultarVeiculosPatioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarVeiculosPatioOperationCompleted);
            }
            this.InvokeAsync("ConsultarVeiculosPatio", new object[] {
                        veiculo}, this.ConsultarVeiculosPatioOperationCompleted, userState);
        }
        
        private void OnConsultarVeiculosPatioOperationCompleted(object arg) {
            if ((this.ConsultarVeiculosPatioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarVeiculosPatioCompleted(this, new ConsultarVeiculosPatioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LiberarVeiculoPatio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string LiberarVeiculoPatio(VeiculoLiberacao veiculo) {
            object[] results = this.Invoke("LiberarVeiculoPatio", new object[] {
                        veiculo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void LiberarVeiculoPatioAsync(VeiculoLiberacao veiculo) {
            this.LiberarVeiculoPatioAsync(veiculo, null);
        }
        
        /// <remarks/>
        public void LiberarVeiculoPatioAsync(VeiculoLiberacao veiculo, object userState) {
            if ((this.LiberarVeiculoPatioOperationCompleted == null)) {
                this.LiberarVeiculoPatioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLiberarVeiculoPatioOperationCompleted);
            }
            this.InvokeAsync("LiberarVeiculoPatio", new object[] {
                        veiculo}, this.LiberarVeiculoPatioOperationCompleted, userState);
        }
        
        private void OnLiberarVeiculoPatioOperationCompleted(object arg) {
            if ((this.LiberarVeiculoPatioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LiberarVeiculoPatioCompleted(this, new LiberarVeiculoPatioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastrarVistoria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CadastrarVistoria(VeiculoVistoria veiculo) {
            object[] results = this.Invoke("CadastrarVistoria", new object[] {
                        veiculo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarVistoriaAsync(VeiculoVistoria veiculo) {
            this.CadastrarVistoriaAsync(veiculo, null);
        }
        
        /// <remarks/>
        public void CadastrarVistoriaAsync(VeiculoVistoria veiculo, object userState) {
            if ((this.CadastrarVistoriaOperationCompleted == null)) {
                this.CadastrarVistoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarVistoriaOperationCompleted);
            }
            this.InvokeAsync("CadastrarVistoria", new object[] {
                        veiculo}, this.CadastrarVistoriaOperationCompleted, userState);
        }
        
        private void OnCadastrarVistoriaOperationCompleted(object arg) {
            if ((this.CadastrarVistoriaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarVistoriaCompleted(this, new CadastrarVistoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/CadastrarExtratoLeilao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CadastrarExtratoLeilao(VeiculoSaidaLeilao veiculo) {
            object[] results = this.Invoke("CadastrarExtratoLeilao", new object[] {
                        veiculo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarExtratoLeilaoAsync(VeiculoSaidaLeilao veiculo) {
            this.CadastrarExtratoLeilaoAsync(veiculo, null);
        }
        
        /// <remarks/>
        public void CadastrarExtratoLeilaoAsync(VeiculoSaidaLeilao veiculo, object userState) {
            if ((this.CadastrarExtratoLeilaoOperationCompleted == null)) {
                this.CadastrarExtratoLeilaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarExtratoLeilaoOperationCompleted);
            }
            this.InvokeAsync("CadastrarExtratoLeilao", new object[] {
                        veiculo}, this.CadastrarExtratoLeilaoOperationCompleted, userState);
        }
        
        private void OnCadastrarExtratoLeilaoOperationCompleted(object arg) {
            if ((this.CadastrarExtratoLeilaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarExtratoLeilaoCompleted(this, new CadastrarExtratoLeilaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarPendenciasLiberacaoVeiculo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarPendenciasLiberacaoVeiculo(VeiculoPendenciaLiberacao veiculo) {
            object[] results = this.Invoke("ConsultarPendenciasLiberacaoVeiculo", new object[] {
                        veiculo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarPendenciasLiberacaoVeiculoAsync(VeiculoPendenciaLiberacao veiculo) {
            this.ConsultarPendenciasLiberacaoVeiculoAsync(veiculo, null);
        }
        
        /// <remarks/>
        public void ConsultarPendenciasLiberacaoVeiculoAsync(VeiculoPendenciaLiberacao veiculo, object userState) {
            if ((this.ConsultarPendenciasLiberacaoVeiculoOperationCompleted == null)) {
                this.ConsultarPendenciasLiberacaoVeiculoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarPendenciasLiberacaoVeiculoOperationCompleted);
            }
            this.InvokeAsync("ConsultarPendenciasLiberacaoVeiculo", new object[] {
                        veiculo}, this.ConsultarPendenciasLiberacaoVeiculoOperationCompleted, userState);
        }
        
        private void OnConsultarPendenciasLiberacaoVeiculoOperationCompleted(object arg) {
            if ((this.ConsultarPendenciasLiberacaoVeiculoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarPendenciasLiberacaoVeiculoCompleted(this, new ConsultarPendenciasLiberacaoVeiculoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarVeiculoParaLeilao", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarVeiculoParaLeilao(VeiculoLeilao veiculo) {
            object[] results = this.Invoke("ConsultarVeiculoParaLeilao", new object[] {
                        veiculo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarVeiculoParaLeilaoAsync(VeiculoLeilao veiculo) {
            this.ConsultarVeiculoParaLeilaoAsync(veiculo, null);
        }
        
        /// <remarks/>
        public void ConsultarVeiculoParaLeilaoAsync(VeiculoLeilao veiculo, object userState) {
            if ((this.ConsultarVeiculoParaLeilaoOperationCompleted == null)) {
                this.ConsultarVeiculoParaLeilaoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarVeiculoParaLeilaoOperationCompleted);
            }
            this.InvokeAsync("ConsultarVeiculoParaLeilao", new object[] {
                        veiculo}, this.ConsultarVeiculoParaLeilaoOperationCompleted, userState);
        }
        
        private void OnConsultarVeiculoParaLeilaoOperationCompleted(object arg) {
            if ((this.ConsultarVeiculoParaLeilaoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarVeiculoParaLeilaoCompleted(this, new ConsultarVeiculoParaLeilaoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarCodigosMunicipios", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarCodigosMunicipios(Municipios veiculo) {
            object[] results = this.Invoke("ConsultarCodigosMunicipios", new object[] {
                        veiculo});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarCodigosMunicipiosAsync(Municipios veiculo) {
            this.ConsultarCodigosMunicipiosAsync(veiculo, null);
        }
        
        /// <remarks/>
        public void ConsultarCodigosMunicipiosAsync(Municipios veiculo, object userState) {
            if ((this.ConsultarCodigosMunicipiosOperationCompleted == null)) {
                this.ConsultarCodigosMunicipiosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarCodigosMunicipiosOperationCompleted);
            }
            this.InvokeAsync("ConsultarCodigosMunicipios", new object[] {
                        veiculo}, this.ConsultarCodigosMunicipiosOperationCompleted, userState);
        }
        
        private void OnConsultarCodigosMunicipiosOperationCompleted(object arg) {
            if ((this.ConsultarCodigosMunicipiosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarCodigosMunicipiosCompleted(this, new ConsultarCodigosMunicipiosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarVeiculo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ConsultarVeiculo(string placa, string operador, string estado) {
            object[] results = this.Invoke("ConsultarVeiculo", new object[] {
                        placa,
                        operador,
                        estado});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarVeiculoAsync(string placa, string operador, string estado) {
            this.ConsultarVeiculoAsync(placa, operador, estado, null);
        }
        
        /// <remarks/>
        public void ConsultarVeiculoAsync(string placa, string operador, string estado, object userState) {
            if ((this.ConsultarVeiculoOperationCompleted == null)) {
                this.ConsultarVeiculoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarVeiculoOperationCompleted);
            }
            this.InvokeAsync("ConsultarVeiculo", new object[] {
                        placa,
                        operador,
                        estado}, this.ConsultarVeiculoOperationCompleted, userState);
        }
        
        private void OnConsultarVeiculoOperationCompleted(object arg) {
            if ((this.ConsultarVeiculoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarVeiculoCompleted(this, new ConsultarVeiculoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ConsultarVeiculoClasse", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public VeiculoConsultaRetorno ConsultarVeiculoClasse(string placa, string operador, string estado) {
            object[] results = this.Invoke("ConsultarVeiculoClasse", new object[] {
                        placa,
                        operador,
                        estado});
            return ((VeiculoConsultaRetorno)(results[0]));
        }
        
        /// <remarks/>
        public void ConsultarVeiculoClasseAsync(string placa, string operador, string estado) {
            this.ConsultarVeiculoClasseAsync(placa, operador, estado, null);
        }
        
        /// <remarks/>
        public void ConsultarVeiculoClasseAsync(string placa, string operador, string estado, object userState) {
            if ((this.ConsultarVeiculoClasseOperationCompleted == null)) {
                this.ConsultarVeiculoClasseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnConsultarVeiculoClasseOperationCompleted);
            }
            this.InvokeAsync("ConsultarVeiculoClasse", new object[] {
                        placa,
                        operador,
                        estado}, this.ConsultarVeiculoClasseOperationCompleted, userState);
        }
        
        private void OnConsultarVeiculoClasseOperationCompleted(object arg) {
            if ((this.ConsultarVeiculoClasseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ConsultarVeiculoClasseCompleted(this, new ConsultarVeiculoClasseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Veiculoinclusao {
        
        private string loginField;
        
        private string tokenField;
        
        private string placaField;
        
        private string chassiField;
        
        private string ufField;
        
        private string numerogrveField;
        
        private string datarecolhimentoField;
        
        private string horarecolhimentoField;
        
        private string classificacaoField;
        
        private string usoreboqueField;
        
        private string dataguardaField;
        
        private string horaguardaField;
        
        private int codigopatioField;
        
        private string operadorField;
        
        private string numeroSerieField;
        
        private int codMultaField;
        
        private string previaDescricaoVistoriaField;
        
        /// <remarks/>
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public string numerogrve {
            get {
                return this.numerogrveField;
            }
            set {
                this.numerogrveField = value;
            }
        }
        
        /// <remarks/>
        public string datarecolhimento {
            get {
                return this.datarecolhimentoField;
            }
            set {
                this.datarecolhimentoField = value;
            }
        }
        
        /// <remarks/>
        public string horarecolhimento {
            get {
                return this.horarecolhimentoField;
            }
            set {
                this.horarecolhimentoField = value;
            }
        }
        
        /// <remarks/>
        public string classificacao {
            get {
                return this.classificacaoField;
            }
            set {
                this.classificacaoField = value;
            }
        }
        
        /// <remarks/>
        public string usoreboque {
            get {
                return this.usoreboqueField;
            }
            set {
                this.usoreboqueField = value;
            }
        }
        
        /// <remarks/>
        public string dataguarda {
            get {
                return this.dataguardaField;
            }
            set {
                this.dataguardaField = value;
            }
        }
        
        /// <remarks/>
        public string horaguarda {
            get {
                return this.horaguardaField;
            }
            set {
                this.horaguardaField = value;
            }
        }
        
        /// <remarks/>
        public int codigopatio {
            get {
                return this.codigopatioField;
            }
            set {
                this.codigopatioField = value;
            }
        }
        
        /// <remarks/>
        public string operador {
            get {
                return this.operadorField;
            }
            set {
                this.operadorField = value;
            }
        }
        
        /// <remarks/>
        public string numeroSerie {
            get {
                return this.numeroSerieField;
            }
            set {
                this.numeroSerieField = value;
            }
        }
        
        /// <remarks/>
        public int CodMulta {
            get {
                return this.codMultaField;
            }
            set {
                this.codMultaField = value;
            }
        }
        
        /// <remarks/>
        public string PreviaDescricaoVistoria {
            get {
                return this.previaDescricaoVistoriaField;
            }
            set {
                this.previaDescricaoVistoriaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RestricoesJuridica {
        
        private int codigoField;
        
        private string restricaoField;
        
        /// <remarks/>
        public int Codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
            }
        }
        
        /// <remarks/>
        public string Restricao {
            get {
                return this.restricaoField;
            }
            set {
                this.restricaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VeiculoConsultaRetorno {
        
        private string retornoField;
        
        private int anoFabricacaoField;
        
        private int anoModeloField;
        
        private int anoUltimaLicencaField;
        
        private double capacidadeCargaField;
        
        private int capacidadePassageirosField;
        
        private int chassiRemarcadoField;
        
        private int numeroRenavamField;
        
        private string chassiField;
        
        private string classificacaoField;
        
        private string codigoCategoriaField;
        
        private string descricaoCategoriaField;
        
        private string descricaoCorField;
        
        private string descricaoMarcaField;
        
        private string descricaoTipoField;
        
        private string informacaoRouboField;
        
        private string pesoBrutoTotalField;
        
        private string placaField;
        
        private string restricaoEstelionatoField;
        
        private string ufField;
        
        private object[] restricoesAdministrativasField;
        
        private RestricoesJuridica[] restricoesJuridicasField;
        
        /// <remarks/>
        public string Retorno {
            get {
                return this.retornoField;
            }
            set {
                this.retornoField = value;
            }
        }
        
        /// <remarks/>
        public int AnoFabricacao {
            get {
                return this.anoFabricacaoField;
            }
            set {
                this.anoFabricacaoField = value;
            }
        }
        
        /// <remarks/>
        public int AnoModelo {
            get {
                return this.anoModeloField;
            }
            set {
                this.anoModeloField = value;
            }
        }
        
        /// <remarks/>
        public int AnoUltimaLicenca {
            get {
                return this.anoUltimaLicencaField;
            }
            set {
                this.anoUltimaLicencaField = value;
            }
        }
        
        /// <remarks/>
        public double CapacidadeCarga {
            get {
                return this.capacidadeCargaField;
            }
            set {
                this.capacidadeCargaField = value;
            }
        }
        
        /// <remarks/>
        public int CapacidadePassageiros {
            get {
                return this.capacidadePassageirosField;
            }
            set {
                this.capacidadePassageirosField = value;
            }
        }
        
        /// <remarks/>
        public int ChassiRemarcado {
            get {
                return this.chassiRemarcadoField;
            }
            set {
                this.chassiRemarcadoField = value;
            }
        }
        
        /// <remarks/>
        public int NumeroRenavam {
            get {
                return this.numeroRenavamField;
            }
            set {
                this.numeroRenavamField = value;
            }
        }
        
        /// <remarks/>
        public string Chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        public string Classificacao {
            get {
                return this.classificacaoField;
            }
            set {
                this.classificacaoField = value;
            }
        }
        
        /// <remarks/>
        public string CodigoCategoria {
            get {
                return this.codigoCategoriaField;
            }
            set {
                this.codigoCategoriaField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoCategoria {
            get {
                return this.descricaoCategoriaField;
            }
            set {
                this.descricaoCategoriaField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoCor {
            get {
                return this.descricaoCorField;
            }
            set {
                this.descricaoCorField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoMarca {
            get {
                return this.descricaoMarcaField;
            }
            set {
                this.descricaoMarcaField = value;
            }
        }
        
        /// <remarks/>
        public string DescricaoTipo {
            get {
                return this.descricaoTipoField;
            }
            set {
                this.descricaoTipoField = value;
            }
        }
        
        /// <remarks/>
        public string InformacaoRoubo {
            get {
                return this.informacaoRouboField;
            }
            set {
                this.informacaoRouboField = value;
            }
        }
        
        /// <remarks/>
        public string PesoBrutoTotal {
            get {
                return this.pesoBrutoTotalField;
            }
            set {
                this.pesoBrutoTotalField = value;
            }
        }
        
        /// <remarks/>
        public string Placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string RestricaoEstelionato {
            get {
                return this.restricaoEstelionatoField;
            }
            set {
                this.restricaoEstelionatoField = value;
            }
        }
        
        /// <remarks/>
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
        
        /// <remarks/>
        public object[] RestricoesAdministrativas {
            get {
                return this.restricoesAdministrativasField;
            }
            set {
                this.restricoesAdministrativasField = value;
            }
        }
        
        /// <remarks/>
        public RestricoesJuridica[] RestricoesJuridicas {
            get {
                return this.restricoesJuridicasField;
            }
            set {
                this.restricoesJuridicasField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Municipios {
        
        private string loginField;
        
        private string tokenField;
        
        private string operadorField;
        
        private string ufField;
        
        /// <remarks/>
        public string Login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string Token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string Operador {
            get {
                return this.operadorField;
            }
            set {
                this.operadorField = value;
            }
        }
        
        /// <remarks/>
        public string Uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VeiculoLeilao {
        
        private string loginField;
        
        private string tokenField;
        
        private string placaField;
        
        private string chassiField;
        
        private string operadorField;
        
        private string ufField;
        
        /// <remarks/>
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        public string operador {
            get {
                return this.operadorField;
            }
            set {
                this.operadorField = value;
            }
        }
        
        /// <remarks/>
        public string uf {
            get {
                return this.ufField;
            }
            set {
                this.ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VeiculoPendenciaLiberacao {
        
        private string loginField;
        
        private string tokenField;
        
        private string placaField;
        
        private string chassiField;
        
        private string operadorField;
        
        private int tipoDocLiberadorField;
        
        private string documentoLiberadorField;
        
        private string numeroGuiaRecolhimentoField;
        
        /// <remarks/>
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        public string operador {
            get {
                return this.operadorField;
            }
            set {
                this.operadorField = value;
            }
        }
        
        /// <remarks/>
        public int tipoDocLiberador {
            get {
                return this.tipoDocLiberadorField;
            }
            set {
                this.tipoDocLiberadorField = value;
            }
        }
        
        /// <remarks/>
        public string documentoLiberador {
            get {
                return this.documentoLiberadorField;
            }
            set {
                this.documentoLiberadorField = value;
            }
        }
        
        /// <remarks/>
        public string numeroGuiaRecolhimento {
            get {
                return this.numeroGuiaRecolhimentoField;
            }
            set {
                this.numeroGuiaRecolhimentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VeiculoSaidaLeilao {
        
        private string loginField;
        
        private string tokenField;
        
        private string placaField;
        
        private string chassiField;
        
        private string descricaoLeilaoField;
        
        private string dataLeilaoField;
        
        private int tipoDocumentoLeiloeiroField;
        
        private string cpfCnpjLeiloeiroField;
        
        private int tipoDocumentoArrematanteField;
        
        private string cpfCnpjArrematanteField;
        
        private string nomeArrematanteField;
        
        private string enderecoArrematanteField;
        
        private string numeroEndArrematanteField;
        
        private string bairroEndArrematanteField;
        
        private string ufEndArrematanteField;
        
        private int codigoMunicipioArrematanteField;
        
        private string cepEndArrematanteField;
        
        private int numeroNotaFiscalField;
        
        private string dataNotaFiscalField;
        
        private string valorNotaFiscalField;
        
        private string renavamField;
        
        private string diarioOficialField;
        
        private string dataDiarioOficialField;
        
        private string operadorField;
        
        private string observacaoField;
        
        /// <remarks/>
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        public string descricaoLeilao {
            get {
                return this.descricaoLeilaoField;
            }
            set {
                this.descricaoLeilaoField = value;
            }
        }
        
        /// <remarks/>
        public string dataLeilao {
            get {
                return this.dataLeilaoField;
            }
            set {
                this.dataLeilaoField = value;
            }
        }
        
        /// <remarks/>
        public int tipoDocumentoLeiloeiro {
            get {
                return this.tipoDocumentoLeiloeiroField;
            }
            set {
                this.tipoDocumentoLeiloeiroField = value;
            }
        }
        
        /// <remarks/>
        public string cpfCnpjLeiloeiro {
            get {
                return this.cpfCnpjLeiloeiroField;
            }
            set {
                this.cpfCnpjLeiloeiroField = value;
            }
        }
        
        /// <remarks/>
        public int tipoDocumentoArrematante {
            get {
                return this.tipoDocumentoArrematanteField;
            }
            set {
                this.tipoDocumentoArrematanteField = value;
            }
        }
        
        /// <remarks/>
        public string cpfCnpjArrematante {
            get {
                return this.cpfCnpjArrematanteField;
            }
            set {
                this.cpfCnpjArrematanteField = value;
            }
        }
        
        /// <remarks/>
        public string nomeArrematante {
            get {
                return this.nomeArrematanteField;
            }
            set {
                this.nomeArrematanteField = value;
            }
        }
        
        /// <remarks/>
        public string enderecoArrematante {
            get {
                return this.enderecoArrematanteField;
            }
            set {
                this.enderecoArrematanteField = value;
            }
        }
        
        /// <remarks/>
        public string numeroEndArrematante {
            get {
                return this.numeroEndArrematanteField;
            }
            set {
                this.numeroEndArrematanteField = value;
            }
        }
        
        /// <remarks/>
        public string bairroEndArrematante {
            get {
                return this.bairroEndArrematanteField;
            }
            set {
                this.bairroEndArrematanteField = value;
            }
        }
        
        /// <remarks/>
        public string ufEndArrematante {
            get {
                return this.ufEndArrematanteField;
            }
            set {
                this.ufEndArrematanteField = value;
            }
        }
        
        /// <remarks/>
        public int codigoMunicipioArrematante {
            get {
                return this.codigoMunicipioArrematanteField;
            }
            set {
                this.codigoMunicipioArrematanteField = value;
            }
        }
        
        /// <remarks/>
        public string cepEndArrematante {
            get {
                return this.cepEndArrematanteField;
            }
            set {
                this.cepEndArrematanteField = value;
            }
        }
        
        /// <remarks/>
        public int numeroNotaFiscal {
            get {
                return this.numeroNotaFiscalField;
            }
            set {
                this.numeroNotaFiscalField = value;
            }
        }
        
        /// <remarks/>
        public string dataNotaFiscal {
            get {
                return this.dataNotaFiscalField;
            }
            set {
                this.dataNotaFiscalField = value;
            }
        }
        
        /// <remarks/>
        public string valorNotaFiscal {
            get {
                return this.valorNotaFiscalField;
            }
            set {
                this.valorNotaFiscalField = value;
            }
        }
        
        /// <remarks/>
        public string renavam {
            get {
                return this.renavamField;
            }
            set {
                this.renavamField = value;
            }
        }
        
        /// <remarks/>
        public string diarioOficial {
            get {
                return this.diarioOficialField;
            }
            set {
                this.diarioOficialField = value;
            }
        }
        
        /// <remarks/>
        public string dataDiarioOficial {
            get {
                return this.dataDiarioOficialField;
            }
            set {
                this.dataDiarioOficialField = value;
            }
        }
        
        /// <remarks/>
        public string operador {
            get {
                return this.operadorField;
            }
            set {
                this.operadorField = value;
            }
        }
        
        /// <remarks/>
        public string observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VeiculoVistoria {
        
        private string loginField;
        
        private string tokenField;
        
        private string placaField;
        
        private string chassiField;
        
        private string estadoVeiculoField;
        
        private string operadorField;
        
        private string observacaoField;
        
        /// <remarks/>
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        public string estadoVeiculo {
            get {
                return this.estadoVeiculoField;
            }
            set {
                this.estadoVeiculoField = value;
            }
        }
        
        /// <remarks/>
        public string operador {
            get {
                return this.operadorField;
            }
            set {
                this.operadorField = value;
            }
        }
        
        /// <remarks/>
        public string Observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VeiculoLiberacao {
        
        private string loginField;
        
        private string tokenField;
        
        private string placaField;
        
        private string chassiField;
        
        private string tipodocumentoliberadorField;
        
        private string cpfcnpjliberadorField;
        
        private string dataliberacaoField;
        
        private string horaliberacaoField;
        
        private string motivoliberacaoField;
        
        private string operadorField;
        
        /// <remarks/>
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        public string tipodocumentoliberador {
            get {
                return this.tipodocumentoliberadorField;
            }
            set {
                this.tipodocumentoliberadorField = value;
            }
        }
        
        /// <remarks/>
        public string cpfcnpjliberador {
            get {
                return this.cpfcnpjliberadorField;
            }
            set {
                this.cpfcnpjliberadorField = value;
            }
        }
        
        /// <remarks/>
        public string dataliberacao {
            get {
                return this.dataliberacaoField;
            }
            set {
                this.dataliberacaoField = value;
            }
        }
        
        /// <remarks/>
        public string horaliberacao {
            get {
                return this.horaliberacaoField;
            }
            set {
                this.horaliberacaoField = value;
            }
        }
        
        /// <remarks/>
        public string motivoliberacao {
            get {
                return this.motivoliberacaoField;
            }
            set {
                this.motivoliberacaoField = value;
            }
        }
        
        /// <remarks/>
        public string operador {
            get {
                return this.operadorField;
            }
            set {
                this.operadorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class VeiculoConsultaPatio {
        
        private string loginField;
        
        private string tokenField;
        
        private string operadorField;
        
        private string placaField;
        
        private string chassiField;
        
        private string somenteMultasRenainfField;
        
        private string somenteAptosLeilaoField;
        
        private string somenteEstadoVeiculoField;
        
        /// <remarks/>
        public string login {
            get {
                return this.loginField;
            }
            set {
                this.loginField = value;
            }
        }
        
        /// <remarks/>
        public string token {
            get {
                return this.tokenField;
            }
            set {
                this.tokenField = value;
            }
        }
        
        /// <remarks/>
        public string operador {
            get {
                return this.operadorField;
            }
            set {
                this.operadorField = value;
            }
        }
        
        /// <remarks/>
        public string placa {
            get {
                return this.placaField;
            }
            set {
                this.placaField = value;
            }
        }
        
        /// <remarks/>
        public string chassi {
            get {
                return this.chassiField;
            }
            set {
                this.chassiField = value;
            }
        }
        
        /// <remarks/>
        public string somenteMultasRenainf {
            get {
                return this.somenteMultasRenainfField;
            }
            set {
                this.somenteMultasRenainfField = value;
            }
        }
        
        /// <remarks/>
        public string somenteAptosLeilao {
            get {
                return this.somenteAptosLeilaoField;
            }
            set {
                this.somenteAptosLeilaoField = value;
            }
        }
        
        /// <remarks/>
        public string somenteEstadoVeiculo {
            get {
                return this.somenteEstadoVeiculoField;
            }
            set {
                this.somenteEstadoVeiculoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void InclusaoVeiculoPatioCompletedEventHandler(object sender, InclusaoVeiculoPatioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class InclusaoVeiculoPatioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal InclusaoVeiculoPatioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ConsultarVeiculosPatioCompletedEventHandler(object sender, ConsultarVeiculosPatioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarVeiculosPatioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarVeiculosPatioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void LiberarVeiculoPatioCompletedEventHandler(object sender, LiberarVeiculoPatioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LiberarVeiculoPatioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LiberarVeiculoPatioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CadastrarVistoriaCompletedEventHandler(object sender, CadastrarVistoriaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarVistoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarVistoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CadastrarExtratoLeilaoCompletedEventHandler(object sender, CadastrarExtratoLeilaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarExtratoLeilaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarExtratoLeilaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ConsultarPendenciasLiberacaoVeiculoCompletedEventHandler(object sender, ConsultarPendenciasLiberacaoVeiculoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarPendenciasLiberacaoVeiculoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarPendenciasLiberacaoVeiculoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ConsultarVeiculoParaLeilaoCompletedEventHandler(object sender, ConsultarVeiculoParaLeilaoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarVeiculoParaLeilaoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarVeiculoParaLeilaoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ConsultarCodigosMunicipiosCompletedEventHandler(object sender, ConsultarCodigosMunicipiosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarCodigosMunicipiosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarCodigosMunicipiosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ConsultarVeiculoCompletedEventHandler(object sender, ConsultarVeiculoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarVeiculoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarVeiculoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void ConsultarVeiculoClasseCompletedEventHandler(object sender, ConsultarVeiculoClasseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ConsultarVeiculoClasseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ConsultarVeiculoClasseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public VeiculoConsultaRetorno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((VeiculoConsultaRetorno)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591