//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobLink.Framework.WebServices.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://179.107.47.90:8088/wsboleto.asmx")]
        public string MobLink_Framework_WebServices_wsboleto_WsBoleto {
            get {
                return ((string)(this["MobLink_Framework_WebServices_wsboleto_WsBoleto"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://179.107.47.90:94/WSPatioxDetran.asmx")]
        public string MobLink_Framework_WebServices_WSPatioxDetran_WSPatioxDetran {
            get {
                return ((string)(this["MobLink_Framework_WebServices_WSPatioxDetran_WSPatioxDetran"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://ws-parceiros.vipleiloes.com/rodandolegal.asmx")]
        public string MobLink_Framework_WebServices__VipBoletoWS_VipBoletoWS {
            get {
                return ((string)(this["MobLink_Framework_WebServices__VipBoletoWS_VipBoletoWS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://apps.correios.com.br/SigepMasterJPA/AtendeClienteService/AtendeCliente")]
        public string MobLink_Framework_WebServices_Correios_AtendeClienteService {
            get {
                return ((string)(this["MobLink_Framework_WebServices_Correios_AtendeClienteService"]));
            }
        }
    }
}
