//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MobLink.Framework.WebServices._VipBoletoWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RodandoLegalSoap", Namespace="http://tempuri.org/")]
    public partial class RodandoLegal : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback FinanceiroFechamentoOperationCompleted;
        
        private System.Threading.SendOrPostCallback FinanceiroDetalhamentoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RodandoLegal() {
            this.Url = global::MobLink.Framework.WebServices.Properties.Settings.Default.MobLink_Framework_WebServices__VipBoletoWS_VipBoletoWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FinanceiroFechamentoCompletedEventHandler FinanceiroFechamentoCompleted;
        
        /// <remarks/>
        public event FinanceiroDetalhamentoCompletedEventHandler FinanceiroDetalhamentoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FinanceiroFechamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FinanceiroFechamento(string usuario, string senha, string Edital) {
            object[] results = this.Invoke("FinanceiroFechamento", new object[] {
                        usuario,
                        senha,
                        Edital});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FinanceiroFechamentoAsync(string usuario, string senha, string Edital) {
            this.FinanceiroFechamentoAsync(usuario, senha, Edital, null);
        }
        
        /// <remarks/>
        public void FinanceiroFechamentoAsync(string usuario, string senha, string Edital, object userState) {
            if ((this.FinanceiroFechamentoOperationCompleted == null)) {
                this.FinanceiroFechamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFinanceiroFechamentoOperationCompleted);
            }
            this.InvokeAsync("FinanceiroFechamento", new object[] {
                        usuario,
                        senha,
                        Edital}, this.FinanceiroFechamentoOperationCompleted, userState);
        }
        
        private void OnFinanceiroFechamentoOperationCompleted(object arg) {
            if ((this.FinanceiroFechamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FinanceiroFechamentoCompleted(this, new FinanceiroFechamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FinanceiroDetalhamento", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FinanceiroDetalhamento(string usuario, string senha, string Edital) {
            object[] results = this.Invoke("FinanceiroDetalhamento", new object[] {
                        usuario,
                        senha,
                        Edital});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FinanceiroDetalhamentoAsync(string usuario, string senha, string Edital) {
            this.FinanceiroDetalhamentoAsync(usuario, senha, Edital, null);
        }
        
        /// <remarks/>
        public void FinanceiroDetalhamentoAsync(string usuario, string senha, string Edital, object userState) {
            if ((this.FinanceiroDetalhamentoOperationCompleted == null)) {
                this.FinanceiroDetalhamentoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFinanceiroDetalhamentoOperationCompleted);
            }
            this.InvokeAsync("FinanceiroDetalhamento", new object[] {
                        usuario,
                        senha,
                        Edital}, this.FinanceiroDetalhamentoOperationCompleted, userState);
        }
        
        private void OnFinanceiroDetalhamentoOperationCompleted(object arg) {
            if ((this.FinanceiroDetalhamentoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FinanceiroDetalhamentoCompleted(this, new FinanceiroDetalhamentoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void FinanceiroFechamentoCompletedEventHandler(object sender, FinanceiroFechamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FinanceiroFechamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FinanceiroFechamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void FinanceiroDetalhamentoCompletedEventHandler(object sender, FinanceiroDetalhamentoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FinanceiroDetalhamentoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FinanceiroDetalhamentoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591