//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MobLink.WSSap.Repositorio.si_ordem_interna_requestService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="si_ordem_interna_requestBinding", Namespace="http://www.l2r.com.br/pi/titulo_ordem_interna")]
    public partial class si_ordem_interna_requestService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback fb70OperationCompleted;
        
        private System.Threading.SendOrPostCallback fb60OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public si_ordem_interna_requestService() {
            this.Url = global::MobLink.WSSap.Repositorio.Properties.Settings.Default.MobLink_WSSap_Repositorio_si_ordem_interna_requestService_si_ordem_interna_requestService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event fb70CompletedEventHandler fb70Completed;
        
        /// <remarks/>
        public event fb60CompletedEventHandler fb60Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void fb70([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.l2r.com.br/pi/titulo_ordem_interna")] dt_titulo_ord_int_fb70 mt_fb70) {
            this.Invoke("fb70", new object[] {
                        mt_fb70});
        }
        
        /// <remarks/>
        public void fb70Async(dt_titulo_ord_int_fb70 mt_fb70) {
            this.fb70Async(mt_fb70, null);
        }
        
        /// <remarks/>
        public void fb70Async(dt_titulo_ord_int_fb70 mt_fb70, object userState) {
            if ((this.fb70OperationCompleted == null)) {
                this.fb70OperationCompleted = new System.Threading.SendOrPostCallback(this.Onfb70OperationCompleted);
            }
            this.InvokeAsync("fb70", new object[] {
                        mt_fb70}, this.fb70OperationCompleted, userState);
        }
        
        private void Onfb70OperationCompleted(object arg) {
            if ((this.fb70Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fb70Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void fb60([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.l2r.com.br/pi/titulo_ordem_interna")] dt_titulo_ord_int_fb60 mt_fb60) {
            this.Invoke("fb60", new object[] {
                        mt_fb60});
        }
        
        /// <remarks/>
        public void fb60Async(dt_titulo_ord_int_fb60 mt_fb60) {
            this.fb60Async(mt_fb60, null);
        }
        
        /// <remarks/>
        public void fb60Async(dt_titulo_ord_int_fb60 mt_fb60, object userState) {
            if ((this.fb60OperationCompleted == null)) {
                this.fb60OperationCompleted = new System.Threading.SendOrPostCallback(this.Onfb60OperationCompleted);
            }
            this.InvokeAsync("fb60", new object[] {
                        mt_fb60}, this.fb60OperationCompleted, userState);
        }
        
        private void Onfb60OperationCompleted(object arg) {
            if ((this.fb60Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fb60Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.l2r.com.br/pi/titulo_ordem_interna")]
    public partial class dt_titulo_ord_int_fb70 {
        
        private string iDTRANSACAOField;
        
        private string bUKRSField;
        
        private string bRNCHField;
        
        private string kUNNRField;
        
        private string bLDATField;
        
        private decimal wRBTRField;
        
        private string bKTXTField;
        
        private string xREF1_HDField;
        
        private string zTERMField;
        
        private decimal wRBTR_LOTEField;
        
        private decimal wRBTR_TAXAField;
        
        private decimal wRBTR_COMField;
        
        private decimal wRBTR_TARIFField;
        
        private bool wRBTR_TARIFFieldSpecified;
        
        private decimal wRBTR_DESCField;
        
        private bool wRBTR_DESCFieldSpecified;
        
        private decimal wRBTR_PAG_MAIORField;
        
        private bool wRBTR_PAG_MAIORFieldSpecified;
        
        private decimal wRBTR_PAGField;
        
        private string hBKIDField;
        
        private string zLSCHField;
        
        private string bLDAT_PAGField;
        
        private string xREF2_HDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string IDTRANSACAO {
            get {
                return this.iDTRANSACAOField;
            }
            set {
                this.iDTRANSACAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRNCH {
            get {
                return this.bRNCHField;
            }
            set {
                this.bRNCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KUNNR {
            get {
                return this.kUNNRField;
            }
            set {
                this.kUNNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BLDAT {
            get {
                return this.bLDATField;
            }
            set {
                this.bLDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WRBTR {
            get {
                return this.wRBTRField;
            }
            set {
                this.wRBTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BKTXT {
            get {
                return this.bKTXTField;
            }
            set {
                this.bKTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XREF1_HD {
            get {
                return this.xREF1_HDField;
            }
            set {
                this.xREF1_HDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTERM {
            get {
                return this.zTERMField;
            }
            set {
                this.zTERMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WRBTR_LOTE {
            get {
                return this.wRBTR_LOTEField;
            }
            set {
                this.wRBTR_LOTEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WRBTR_TAXA {
            get {
                return this.wRBTR_TAXAField;
            }
            set {
                this.wRBTR_TAXAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WRBTR_COM {
            get {
                return this.wRBTR_COMField;
            }
            set {
                this.wRBTR_COMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WRBTR_TARIF {
            get {
                return this.wRBTR_TARIFField;
            }
            set {
                this.wRBTR_TARIFField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WRBTR_TARIFSpecified {
            get {
                return this.wRBTR_TARIFFieldSpecified;
            }
            set {
                this.wRBTR_TARIFFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WRBTR_DESC {
            get {
                return this.wRBTR_DESCField;
            }
            set {
                this.wRBTR_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WRBTR_DESCSpecified {
            get {
                return this.wRBTR_DESCFieldSpecified;
            }
            set {
                this.wRBTR_DESCFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WRBTR_PAG_MAIOR {
            get {
                return this.wRBTR_PAG_MAIORField;
            }
            set {
                this.wRBTR_PAG_MAIORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool WRBTR_PAG_MAIORSpecified {
            get {
                return this.wRBTR_PAG_MAIORFieldSpecified;
            }
            set {
                this.wRBTR_PAG_MAIORFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WRBTR_PAG {
            get {
                return this.wRBTR_PAGField;
            }
            set {
                this.wRBTR_PAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HBKID {
            get {
                return this.hBKIDField;
            }
            set {
                this.hBKIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZLSCH {
            get {
                return this.zLSCHField;
            }
            set {
                this.zLSCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BLDAT_PAG {
            get {
                return this.bLDAT_PAGField;
            }
            set {
                this.bLDAT_PAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XREF2_HD {
            get {
                return this.xREF2_HDField;
            }
            set {
                this.xREF2_HDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.l2r.com.br/pi/titulo_ordem_interna")]
    public partial class dt_titulo_ord_int_fb60 {
        
        private string iDTRANSACAOField;
        
        private string bUKRSField;
        
        private string bRNCHField;
        
        private string lIFNRField;
        
        private string bLDATField;
        
        private decimal wRBTRField;
        
        private string bKTXTField;
        
        private string xREF1_HDField;
        
        private string zTERMField;
        
        private string zFBDTField;
        
        private string xBLNRField;
        
        private dt_titulo_ord_int_fb60ITEMS[] iTEMSField;
        
        private decimal wRBTR_PAGField;
        
        private string hBKIDField;
        
        private string zLSCHField;
        
        private string bLDAT_PAGField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string IDTRANSACAO {
            get {
                return this.iDTRANSACAOField;
            }
            set {
                this.iDTRANSACAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BRNCH {
            get {
                return this.bRNCHField;
            }
            set {
                this.bRNCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LIFNR {
            get {
                return this.lIFNRField;
            }
            set {
                this.lIFNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BLDAT {
            get {
                return this.bLDATField;
            }
            set {
                this.bLDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WRBTR {
            get {
                return this.wRBTRField;
            }
            set {
                this.wRBTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BKTXT {
            get {
                return this.bKTXTField;
            }
            set {
                this.bKTXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XREF1_HD {
            get {
                return this.xREF1_HDField;
            }
            set {
                this.xREF1_HDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTERM {
            get {
                return this.zTERMField;
            }
            set {
                this.zTERMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZFBDT {
            get {
                return this.zFBDTField;
            }
            set {
                this.zFBDTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string XBLNR {
            get {
                return this.xBLNRField;
            }
            set {
                this.xBLNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEMS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_titulo_ord_int_fb60ITEMS[] ITEMS {
            get {
                return this.iTEMSField;
            }
            set {
                this.iTEMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal WRBTR_PAG {
            get {
                return this.wRBTR_PAGField;
            }
            set {
                this.wRBTR_PAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HBKID {
            get {
                return this.hBKIDField;
            }
            set {
                this.hBKIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZLSCH {
            get {
                return this.zLSCHField;
            }
            set {
                this.zLSCHField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BLDAT_PAG {
            get {
                return this.bLDAT_PAGField;
            }
            set {
                this.bLDAT_PAGField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.l2r.com.br/pi/titulo_ordem_interna")]
    public partial class dt_titulo_ord_int_fb60ITEMS {
        
        private string hKONTField;
        
        private decimal iTM_WRBTRField;
        
        private string kOSTLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HKONT {
            get {
                return this.hKONTField;
            }
            set {
                this.hKONTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal ITM_WRBTR {
            get {
                return this.iTM_WRBTRField;
            }
            set {
                this.iTM_WRBTRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KOSTL {
            get {
                return this.kOSTLField;
            }
            set {
                this.kOSTLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void fb70CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void fb60CompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591