//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace TransmissaoFB70.WSSapLinkPatios {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSSapLinkPatiosSoap", Namespace="http://linkpatios/")]
    public partial class WSSapLinkPatios : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TesteOrdemVendaOperationCompleted;
        
        private System.Threading.SendOrPostCallback FB70OperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarClienteSAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback CadastrarOrdemVendaSAPOperationCompleted;
        
        private System.Threading.SendOrPostCallback IngressaTransacaoSAPOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSSapLinkPatios() {
            this.Url = global::TransmissaoFB70.Properties.Settings.Default.TransmissaoFB70_WSSapLinkPatios_WSSapLinkPatios;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TesteOrdemVendaCompletedEventHandler TesteOrdemVendaCompleted;
        
        /// <remarks/>
        public event FB70CompletedEventHandler FB70Completed;
        
        /// <remarks/>
        public event CadastrarClienteSAPCompletedEventHandler CadastrarClienteSAPCompleted;
        
        /// <remarks/>
        public event CadastrarOrdemVendaSAPCompletedEventHandler CadastrarOrdemVendaSAPCompleted;
        
        /// <remarks/>
        public event IngressaTransacaoSAPCompletedEventHandler IngressaTransacaoSAPCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://linkpatios/TesteOrdemVenda", RequestNamespace="http://linkpatios/", ResponseNamespace="http://linkpatios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TesteOrdemVenda(int value) {
            object[] results = this.Invoke("TesteOrdemVenda", new object[] {
                        value});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TesteOrdemVendaAsync(int value) {
            this.TesteOrdemVendaAsync(value, null);
        }
        
        /// <remarks/>
        public void TesteOrdemVendaAsync(int value, object userState) {
            if ((this.TesteOrdemVendaOperationCompleted == null)) {
                this.TesteOrdemVendaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTesteOrdemVendaOperationCompleted);
            }
            this.InvokeAsync("TesteOrdemVenda", new object[] {
                        value}, this.TesteOrdemVendaOperationCompleted, userState);
        }
        
        private void OnTesteOrdemVendaOperationCompleted(object arg) {
            if ((this.TesteOrdemVendaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TesteOrdemVendaCompleted(this, new TesteOrdemVendaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://linkpatios/FB70", RequestNamespace="http://linkpatios/", ResponseNamespace="http://linkpatios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Retorno FB70(OrdemInternaFB70 Entrada) {
            object[] results = this.Invoke("FB70", new object[] {
                        Entrada});
            return ((Retorno)(results[0]));
        }
        
        /// <remarks/>
        public void FB70Async(OrdemInternaFB70 Entrada) {
            this.FB70Async(Entrada, null);
        }
        
        /// <remarks/>
        public void FB70Async(OrdemInternaFB70 Entrada, object userState) {
            if ((this.FB70OperationCompleted == null)) {
                this.FB70OperationCompleted = new System.Threading.SendOrPostCallback(this.OnFB70OperationCompleted);
            }
            this.InvokeAsync("FB70", new object[] {
                        Entrada}, this.FB70OperationCompleted, userState);
        }
        
        private void OnFB70OperationCompleted(object arg) {
            if ((this.FB70Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FB70Completed(this, new FB70CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://linkpatios/CadastrarClienteSAP", RequestNamespace="http://linkpatios/", ResponseNamespace="http://linkpatios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Retorno CadastrarClienteSAP(ClienteSap Cliente) {
            object[] results = this.Invoke("CadastrarClienteSAP", new object[] {
                        Cliente});
            return ((Retorno)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarClienteSAPAsync(ClienteSap Cliente) {
            this.CadastrarClienteSAPAsync(Cliente, null);
        }
        
        /// <remarks/>
        public void CadastrarClienteSAPAsync(ClienteSap Cliente, object userState) {
            if ((this.CadastrarClienteSAPOperationCompleted == null)) {
                this.CadastrarClienteSAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarClienteSAPOperationCompleted);
            }
            this.InvokeAsync("CadastrarClienteSAP", new object[] {
                        Cliente}, this.CadastrarClienteSAPOperationCompleted, userState);
        }
        
        private void OnCadastrarClienteSAPOperationCompleted(object arg) {
            if ((this.CadastrarClienteSAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarClienteSAPCompleted(this, new CadastrarClienteSAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://linkpatios/CadastrarOrdemVendaSAP", RequestNamespace="http://linkpatios/", ResponseNamespace="http://linkpatios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Retorno CadastrarOrdemVendaSAP(OrdemVendaSAP OrdemVenda) {
            object[] results = this.Invoke("CadastrarOrdemVendaSAP", new object[] {
                        OrdemVenda});
            return ((Retorno)(results[0]));
        }
        
        /// <remarks/>
        public void CadastrarOrdemVendaSAPAsync(OrdemVendaSAP OrdemVenda) {
            this.CadastrarOrdemVendaSAPAsync(OrdemVenda, null);
        }
        
        /// <remarks/>
        public void CadastrarOrdemVendaSAPAsync(OrdemVendaSAP OrdemVenda, object userState) {
            if ((this.CadastrarOrdemVendaSAPOperationCompleted == null)) {
                this.CadastrarOrdemVendaSAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCadastrarOrdemVendaSAPOperationCompleted);
            }
            this.InvokeAsync("CadastrarOrdemVendaSAP", new object[] {
                        OrdemVenda}, this.CadastrarOrdemVendaSAPOperationCompleted, userState);
        }
        
        private void OnCadastrarOrdemVendaSAPOperationCompleted(object arg) {
            if ((this.CadastrarOrdemVendaSAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CadastrarOrdemVendaSAPCompleted(this, new CadastrarOrdemVendaSAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://linkpatios/IngressaTransacaoSAP", RequestNamespace="http://linkpatios/", ResponseNamespace="http://linkpatios/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Retorno IngressaTransacaoSAP(Transacao Transacao) {
            object[] results = this.Invoke("IngressaTransacaoSAP", new object[] {
                        Transacao});
            return ((Retorno)(results[0]));
        }
        
        /// <remarks/>
        public void IngressaTransacaoSAPAsync(Transacao Transacao) {
            this.IngressaTransacaoSAPAsync(Transacao, null);
        }
        
        /// <remarks/>
        public void IngressaTransacaoSAPAsync(Transacao Transacao, object userState) {
            if ((this.IngressaTransacaoSAPOperationCompleted == null)) {
                this.IngressaTransacaoSAPOperationCompleted = new System.Threading.SendOrPostCallback(this.OnIngressaTransacaoSAPOperationCompleted);
            }
            this.InvokeAsync("IngressaTransacaoSAP", new object[] {
                        Transacao}, this.IngressaTransacaoSAPOperationCompleted, userState);
        }
        
        private void OnIngressaTransacaoSAPOperationCompleted(object arg) {
            if ((this.IngressaTransacaoSAPCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.IngressaTransacaoSAPCompleted(this, new IngressaTransacaoSAPCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://linkpatios/")]
    public partial class OrdemInternaFB70 {
        
        private string numero_ordem_internaField;
        
        private string data_faturaField;
        
        private string data_pagamentoField;
        
        private string codigo_empresaField;
        
        private string codigo_bancoField;
        
        private string transacaoField;
        
        private string codigo_clienteField;
        
        private decimal montante_brutoField;
        
        private decimal valor_comissaoField;
        
        private decimal valor_descontoField;
        
        private bool opcao_valor_descontoField;
        
        private decimal valor_loteField;
        
        private decimal valor_total_pagoField;
        
        private decimal valor_pagamento_maiorField;
        
        private bool opcao_valor_pagamento_maiorField;
        
        private decimal valor_tarifa_bancariaField;
        
        private bool opcao_valor_tarifa_bancariaField;
        
        private decimal valor_taxa_administrativaField;
        
        private string identificacao_leilao_patio_loteField;
        
        private string numero_boleto_pagamentoField;
        
        private string forma_pagamentoField;
        
        private string condicao_pagamentoField;
        
        /// <remarks/>
        public string numero_ordem_interna {
            get {
                return this.numero_ordem_internaField;
            }
            set {
                this.numero_ordem_internaField = value;
            }
        }
        
        /// <remarks/>
        public string data_fatura {
            get {
                return this.data_faturaField;
            }
            set {
                this.data_faturaField = value;
            }
        }
        
        /// <remarks/>
        public string data_pagamento {
            get {
                return this.data_pagamentoField;
            }
            set {
                this.data_pagamentoField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_empresa {
            get {
                return this.codigo_empresaField;
            }
            set {
                this.codigo_empresaField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_banco {
            get {
                return this.codigo_bancoField;
            }
            set {
                this.codigo_bancoField = value;
            }
        }
        
        /// <remarks/>
        public string transacao {
            get {
                return this.transacaoField;
            }
            set {
                this.transacaoField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_cliente {
            get {
                return this.codigo_clienteField;
            }
            set {
                this.codigo_clienteField = value;
            }
        }
        
        /// <remarks/>
        public decimal montante_bruto {
            get {
                return this.montante_brutoField;
            }
            set {
                this.montante_brutoField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor_comissao {
            get {
                return this.valor_comissaoField;
            }
            set {
                this.valor_comissaoField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor_desconto {
            get {
                return this.valor_descontoField;
            }
            set {
                this.valor_descontoField = value;
            }
        }
        
        /// <remarks/>
        public bool opcao_valor_desconto {
            get {
                return this.opcao_valor_descontoField;
            }
            set {
                this.opcao_valor_descontoField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor_lote {
            get {
                return this.valor_loteField;
            }
            set {
                this.valor_loteField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor_total_pago {
            get {
                return this.valor_total_pagoField;
            }
            set {
                this.valor_total_pagoField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor_pagamento_maior {
            get {
                return this.valor_pagamento_maiorField;
            }
            set {
                this.valor_pagamento_maiorField = value;
            }
        }
        
        /// <remarks/>
        public bool opcao_valor_pagamento_maior {
            get {
                return this.opcao_valor_pagamento_maiorField;
            }
            set {
                this.opcao_valor_pagamento_maiorField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor_tarifa_bancaria {
            get {
                return this.valor_tarifa_bancariaField;
            }
            set {
                this.valor_tarifa_bancariaField = value;
            }
        }
        
        /// <remarks/>
        public bool opcao_valor_tarifa_bancaria {
            get {
                return this.opcao_valor_tarifa_bancariaField;
            }
            set {
                this.opcao_valor_tarifa_bancariaField = value;
            }
        }
        
        /// <remarks/>
        public decimal valor_taxa_administrativa {
            get {
                return this.valor_taxa_administrativaField;
            }
            set {
                this.valor_taxa_administrativaField = value;
            }
        }
        
        /// <remarks/>
        public string identificacao_leilao_patio_lote {
            get {
                return this.identificacao_leilao_patio_loteField;
            }
            set {
                this.identificacao_leilao_patio_loteField = value;
            }
        }
        
        /// <remarks/>
        public string numero_boleto_pagamento {
            get {
                return this.numero_boleto_pagamentoField;
            }
            set {
                this.numero_boleto_pagamentoField = value;
            }
        }
        
        /// <remarks/>
        public string forma_pagamento {
            get {
                return this.forma_pagamentoField;
            }
            set {
                this.forma_pagamentoField = value;
            }
        }
        
        /// <remarks/>
        public string condicao_pagamento {
            get {
                return this.condicao_pagamentoField;
            }
            set {
                this.condicao_pagamentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://linkpatios/")]
    public partial class Transacao {
        
        private int idTransacaoField;
        
        private string retDocIdField;
        
        private string retMensagensField;
        
        private string retnotaField;
        
        private string retdtemissaoField;
        
        /// <remarks/>
        public int idTransacao {
            get {
                return this.idTransacaoField;
            }
            set {
                this.idTransacaoField = value;
            }
        }
        
        /// <remarks/>
        public string retDocId {
            get {
                return this.retDocIdField;
            }
            set {
                this.retDocIdField = value;
            }
        }
        
        /// <remarks/>
        public string retMensagens {
            get {
                return this.retMensagensField;
            }
            set {
                this.retMensagensField = value;
            }
        }
        
        /// <remarks/>
        public string retnota {
            get {
                return this.retnotaField;
            }
            set {
                this.retnotaField = value;
            }
        }
        
        /// <remarks/>
        public string retdtemissao {
            get {
                return this.retdtemissaoField;
            }
            set {
                this.retdtemissaoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://linkpatios/")]
    public partial class DOC_PAGAM {
        
        private string meioPagamentoField;
        
        private string numeroDocumentoField;
        
        /// <remarks/>
        public string meioPagamento {
            get {
                return this.meioPagamentoField;
            }
            set {
                this.meioPagamentoField = value;
            }
        }
        
        /// <remarks/>
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://linkpatios/")]
    public partial class ITEMS {
        
        private string codigoMaterialField;
        
        private decimal quantidadeField;
        
        private decimal valorBrutoField;
        
        private decimal valorComDescontoField;
        
        private string codigoOrdemField;
        
        private string tipoDocumentoField;
        
        private string textoCabecalhoField;
        
        private int idAtendimentoField;
        
        private string tipoComposicaoField;
        
        private int[] listaIDFaturamentoComposicaoField;
        
        private System.Nullable<int> id_grupoField;
        
        private string codigo_material_agrupamentoField;
        
        /// <remarks/>
        public string codigoMaterial {
            get {
                return this.codigoMaterialField;
            }
            set {
                this.codigoMaterialField = value;
            }
        }
        
        /// <remarks/>
        public decimal quantidade {
            get {
                return this.quantidadeField;
            }
            set {
                this.quantidadeField = value;
            }
        }
        
        /// <remarks/>
        public decimal valorBruto {
            get {
                return this.valorBrutoField;
            }
            set {
                this.valorBrutoField = value;
            }
        }
        
        /// <remarks/>
        public decimal valorComDesconto {
            get {
                return this.valorComDescontoField;
            }
            set {
                this.valorComDescontoField = value;
            }
        }
        
        /// <remarks/>
        public string codigoOrdem {
            get {
                return this.codigoOrdemField;
            }
            set {
                this.codigoOrdemField = value;
            }
        }
        
        /// <remarks/>
        public string tipoDocumento {
            get {
                return this.tipoDocumentoField;
            }
            set {
                this.tipoDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string textoCabecalho {
            get {
                return this.textoCabecalhoField;
            }
            set {
                this.textoCabecalhoField = value;
            }
        }
        
        /// <remarks/>
        public int IdAtendimento {
            get {
                return this.idAtendimentoField;
            }
            set {
                this.idAtendimentoField = value;
            }
        }
        
        /// <remarks/>
        public string tipoComposicao {
            get {
                return this.tipoComposicaoField;
            }
            set {
                this.tipoComposicaoField = value;
            }
        }
        
        /// <remarks/>
        public int[] ListaIDFaturamentoComposicao {
            get {
                return this.listaIDFaturamentoComposicaoField;
            }
            set {
                this.listaIDFaturamentoComposicaoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> id_grupo {
            get {
                return this.id_grupoField;
            }
            set {
                this.id_grupoField = value;
            }
        }
        
        /// <remarks/>
        public string codigo_material_agrupamento {
            get {
                return this.codigo_material_agrupamentoField;
            }
            set {
                this.codigo_material_agrupamentoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://linkpatios/")]
    public partial class OrdemVendaSAP {
        
        private int iDTRANSACAOField;
        
        private string centroField;
        
        private string numeroContratoField;
        
        private string codigoClienteField;
        
        private string codigoPedidoField;
        
        private string textoCabecalhoField;
        
        private ITEMS[] itensVendaField;
        
        private DOC_PAGAM[] documentosPagamentoField;
        
        private string numeroProcessoField;
        
        private string periodoField;
        
        private string numeroLeilaoPatioLoteField;
        
        /// <remarks/>
        public int IDTRANSACAO {
            get {
                return this.iDTRANSACAOField;
            }
            set {
                this.iDTRANSACAOField = value;
            }
        }
        
        /// <remarks/>
        public string centro {
            get {
                return this.centroField;
            }
            set {
                this.centroField = value;
            }
        }
        
        /// <remarks/>
        public string numeroContrato {
            get {
                return this.numeroContratoField;
            }
            set {
                this.numeroContratoField = value;
            }
        }
        
        /// <remarks/>
        public string codigoCliente {
            get {
                return this.codigoClienteField;
            }
            set {
                this.codigoClienteField = value;
            }
        }
        
        /// <remarks/>
        public string codigoPedido {
            get {
                return this.codigoPedidoField;
            }
            set {
                this.codigoPedidoField = value;
            }
        }
        
        /// <remarks/>
        public string textoCabecalho {
            get {
                return this.textoCabecalhoField;
            }
            set {
                this.textoCabecalhoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ITEMS[] itensVenda {
            get {
                return this.itensVendaField;
            }
            set {
                this.itensVendaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public DOC_PAGAM[] documentosPagamento {
            get {
                return this.documentosPagamentoField;
            }
            set {
                this.documentosPagamentoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroProcesso {
            get {
                return this.numeroProcessoField;
            }
            set {
                this.numeroProcessoField = value;
            }
        }
        
        /// <remarks/>
        public string Periodo {
            get {
                return this.periodoField;
            }
            set {
                this.periodoField = value;
            }
        }
        
        /// <remarks/>
        public string NumeroLeilaoPatioLote {
            get {
                return this.numeroLeilaoPatioLoteField;
            }
            set {
                this.numeroLeilaoPatioLoteField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://linkpatios/")]
    public partial class ClienteSap {
        
        private int transacao_SAPField;
        
        private string codigo_EmpresaField;
        
        private string organizacao_VendasField;
        
        private string nome_ClienteField;
        
        private string endereco_RuaField;
        
        private string endereco_NumeroField;
        
        private string endereco_EdificioField;
        
        private string endereco_Edificio_AndarField;
        
        private string endereco_BairroField;
        
        private string endereco_CEPField;
        
        private string endereco_CidadeField;
        
        private string endereco_RegiaoField;
        
        private string telefoneField;
        
        private string emailField;
        
        private string cNPJField;
        
        private string cPFField;
        
        private string inscricao_EstadualField;
        
        private string inscricao_MunicipalField;
        
        private string forma_PagamentoField;
        
        private string condicao_PagamentoField;
        
        private string endereco_PaisField;
        
        private string tipo_ParceiroField;
        
        private string codigo_ParceiroField;
        
        private string codigo_Organizacao_ParceiroField;
        
        private int id_GRVField;
        
        /// <remarks/>
        public int Transacao_SAP {
            get {
                return this.transacao_SAPField;
            }
            set {
                this.transacao_SAPField = value;
            }
        }
        
        /// <remarks/>
        public string Codigo_Empresa {
            get {
                return this.codigo_EmpresaField;
            }
            set {
                this.codigo_EmpresaField = value;
            }
        }
        
        /// <remarks/>
        public string Organizacao_Vendas {
            get {
                return this.organizacao_VendasField;
            }
            set {
                this.organizacao_VendasField = value;
            }
        }
        
        /// <remarks/>
        public string Nome_Cliente {
            get {
                return this.nome_ClienteField;
            }
            set {
                this.nome_ClienteField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco_Rua {
            get {
                return this.endereco_RuaField;
            }
            set {
                this.endereco_RuaField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco_Numero {
            get {
                return this.endereco_NumeroField;
            }
            set {
                this.endereco_NumeroField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco_Edificio {
            get {
                return this.endereco_EdificioField;
            }
            set {
                this.endereco_EdificioField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco_Edificio_Andar {
            get {
                return this.endereco_Edificio_AndarField;
            }
            set {
                this.endereco_Edificio_AndarField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco_Bairro {
            get {
                return this.endereco_BairroField;
            }
            set {
                this.endereco_BairroField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco_CEP {
            get {
                return this.endereco_CEPField;
            }
            set {
                this.endereco_CEPField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco_Cidade {
            get {
                return this.endereco_CidadeField;
            }
            set {
                this.endereco_CidadeField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco_Regiao {
            get {
                return this.endereco_RegiaoField;
            }
            set {
                this.endereco_RegiaoField = value;
            }
        }
        
        /// <remarks/>
        public string Telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string CNPJ {
            get {
                return this.cNPJField;
            }
            set {
                this.cNPJField = value;
            }
        }
        
        /// <remarks/>
        public string CPF {
            get {
                return this.cPFField;
            }
            set {
                this.cPFField = value;
            }
        }
        
        /// <remarks/>
        public string Inscricao_Estadual {
            get {
                return this.inscricao_EstadualField;
            }
            set {
                this.inscricao_EstadualField = value;
            }
        }
        
        /// <remarks/>
        public string Inscricao_Municipal {
            get {
                return this.inscricao_MunicipalField;
            }
            set {
                this.inscricao_MunicipalField = value;
            }
        }
        
        /// <remarks/>
        public string Forma_Pagamento {
            get {
                return this.forma_PagamentoField;
            }
            set {
                this.forma_PagamentoField = value;
            }
        }
        
        /// <remarks/>
        public string Condicao_Pagamento {
            get {
                return this.condicao_PagamentoField;
            }
            set {
                this.condicao_PagamentoField = value;
            }
        }
        
        /// <remarks/>
        public string Endereco_Pais {
            get {
                return this.endereco_PaisField;
            }
            set {
                this.endereco_PaisField = value;
            }
        }
        
        /// <remarks/>
        public string Tipo_Parceiro {
            get {
                return this.tipo_ParceiroField;
            }
            set {
                this.tipo_ParceiroField = value;
            }
        }
        
        /// <remarks/>
        public string Codigo_Parceiro {
            get {
                return this.codigo_ParceiroField;
            }
            set {
                this.codigo_ParceiroField = value;
            }
        }
        
        /// <remarks/>
        public string Codigo_Organizacao_Parceiro {
            get {
                return this.codigo_Organizacao_ParceiroField;
            }
            set {
                this.codigo_Organizacao_ParceiroField = value;
            }
        }
        
        /// <remarks/>
        public int Id_GRV {
            get {
                return this.id_GRVField;
            }
            set {
                this.id_GRVField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://linkpatios/")]
    public partial class Retorno {
        
        private bool resultadoField;
        
        private string mensagemField;
        
        /// <remarks/>
        public bool Resultado {
            get {
                return this.resultadoField;
            }
            set {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        public string Mensagem {
            get {
                return this.mensagemField;
            }
            set {
                this.mensagemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void TesteOrdemVendaCompletedEventHandler(object sender, TesteOrdemVendaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TesteOrdemVendaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TesteOrdemVendaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void FB70CompletedEventHandler(object sender, FB70CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FB70CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FB70CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Retorno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Retorno)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CadastrarClienteSAPCompletedEventHandler(object sender, CadastrarClienteSAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarClienteSAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarClienteSAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Retorno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Retorno)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void CadastrarOrdemVendaSAPCompletedEventHandler(object sender, CadastrarOrdemVendaSAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CadastrarOrdemVendaSAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CadastrarOrdemVendaSAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Retorno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Retorno)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void IngressaTransacaoSAPCompletedEventHandler(object sender, IngressaTransacaoSAPCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class IngressaTransacaoSAPCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal IngressaTransacaoSAPCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Retorno Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Retorno)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591