//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MobLink.Framework.WebServices._WSBoleto {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WsBoletoSoap", Namespace="http://tempuri.org/")]
    public partial class WsBoleto : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BoletoBradescoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BoletoBancosOperationCompleted;
        
        private System.Threading.SendOrPostCallback BoletoBancosRetornoLinhaOperationCompleted;
        
        private System.Threading.SendOrPostCallback FaturaConcessionariaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BoletoBancosRemessaOperationCompleted;
        
        private System.Threading.SendOrPostCallback BoletoCaixaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WsBoleto() {
            this.Url = global::MobLink.Framework.WebServices.Properties.Settings.Default.MobLink_Framework_WebServices_wsboleto_WsBoleto;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BoletoBradescoCompletedEventHandler BoletoBradescoCompleted;
        
        /// <remarks/>
        public event BoletoBancosCompletedEventHandler BoletoBancosCompleted;
        
        /// <remarks/>
        public event BoletoBancosRetornoLinhaCompletedEventHandler BoletoBancosRetornoLinhaCompleted;
        
        /// <remarks/>
        public event FaturaConcessionariaCompletedEventHandler FaturaConcessionariaCompleted;
        
        /// <remarks/>
        public event BoletoBancosRemessaCompletedEventHandler BoletoBancosRemessaCompleted;
        
        /// <remarks/>
        public event BoletoCaixaCompletedEventHandler BoletoCaixaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BoletoBradesco", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] BoletoBradesco(BoletoBradesco boleto, string Tipo) {
            object[] results = this.Invoke("BoletoBradesco", new object[] {
                        boleto,
                        Tipo});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void BoletoBradescoAsync(BoletoBradesco boleto, string Tipo) {
            this.BoletoBradescoAsync(boleto, Tipo, null);
        }
        
        /// <remarks/>
        public void BoletoBradescoAsync(BoletoBradesco boleto, string Tipo, object userState) {
            if ((this.BoletoBradescoOperationCompleted == null)) {
                this.BoletoBradescoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBoletoBradescoOperationCompleted);
            }
            this.InvokeAsync("BoletoBradesco", new object[] {
                        boleto,
                        Tipo}, this.BoletoBradescoOperationCompleted, userState);
        }
        
        private void OnBoletoBradescoOperationCompleted(object arg) {
            if ((this.BoletoBradescoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BoletoBradescoCompleted(this, new BoletoBradescoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BoletoBancos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] BoletoBancos(BoletoTodos boleto, string Tipo) {
            object[] results = this.Invoke("BoletoBancos", new object[] {
                        boleto,
                        Tipo});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void BoletoBancosAsync(BoletoTodos boleto, string Tipo) {
            this.BoletoBancosAsync(boleto, Tipo, null);
        }
        
        /// <remarks/>
        public void BoletoBancosAsync(BoletoTodos boleto, string Tipo, object userState) {
            if ((this.BoletoBancosOperationCompleted == null)) {
                this.BoletoBancosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBoletoBancosOperationCompleted);
            }
            this.InvokeAsync("BoletoBancos", new object[] {
                        boleto,
                        Tipo}, this.BoletoBancosOperationCompleted, userState);
        }
        
        private void OnBoletoBancosOperationCompleted(object arg) {
            if ((this.BoletoBancosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BoletoBancosCompleted(this, new BoletoBancosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BoletoBancosRetornoLinha", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] BoletoBancosRetornoLinha(BoletoTodos boleto, string login, string senha, string Tipo, bool isdev, out string linha, out int linha_id) {
            object[] results = this.Invoke("BoletoBancosRetornoLinha", new object[] {
                        boleto,
                        login,
                        senha,
                        Tipo,
                        isdev});
            linha = ((string)(results[1]));
            linha_id = ((int)(results[2]));
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void BoletoBancosRetornoLinhaAsync(BoletoTodos boleto, string login, string senha, string Tipo, bool isdev) {
            this.BoletoBancosRetornoLinhaAsync(boleto, login, senha, Tipo, isdev, null);
        }
        
        /// <remarks/>
        public void BoletoBancosRetornoLinhaAsync(BoletoTodos boleto, string login, string senha, string Tipo, bool isdev, object userState) {
            if ((this.BoletoBancosRetornoLinhaOperationCompleted == null)) {
                this.BoletoBancosRetornoLinhaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBoletoBancosRetornoLinhaOperationCompleted);
            }
            this.InvokeAsync("BoletoBancosRetornoLinha", new object[] {
                        boleto,
                        login,
                        senha,
                        Tipo,
                        isdev}, this.BoletoBancosRetornoLinhaOperationCompleted, userState);
        }
        
        private void OnBoletoBancosRetornoLinhaOperationCompleted(object arg) {
            if ((this.BoletoBancosRetornoLinhaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BoletoBancosRetornoLinhaCompleted(this, new BoletoBancosRetornoLinhaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FaturaConcessionaria", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FaturaConcessionaria(BoletoConcessionaria boleto, string Tipo) {
            object[] results = this.Invoke("FaturaConcessionaria", new object[] {
                        boleto,
                        Tipo});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void FaturaConcessionariaAsync(BoletoConcessionaria boleto, string Tipo) {
            this.FaturaConcessionariaAsync(boleto, Tipo, null);
        }
        
        /// <remarks/>
        public void FaturaConcessionariaAsync(BoletoConcessionaria boleto, string Tipo, object userState) {
            if ((this.FaturaConcessionariaOperationCompleted == null)) {
                this.FaturaConcessionariaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFaturaConcessionariaOperationCompleted);
            }
            this.InvokeAsync("FaturaConcessionaria", new object[] {
                        boleto,
                        Tipo}, this.FaturaConcessionariaOperationCompleted, userState);
        }
        
        private void OnFaturaConcessionariaOperationCompleted(object arg) {
            if ((this.FaturaConcessionariaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FaturaConcessionariaCompleted(this, new FaturaConcessionariaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BoletoBancosRemessa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] BoletoBancosRemessa(BoletoTodos boleto, string Tipo, out string remessa_retorno) {
            object[] results = this.Invoke("BoletoBancosRemessa", new object[] {
                        boleto,
                        Tipo});
            remessa_retorno = ((string)(results[1]));
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void BoletoBancosRemessaAsync(BoletoTodos boleto, string Tipo) {
            this.BoletoBancosRemessaAsync(boleto, Tipo, null);
        }
        
        /// <remarks/>
        public void BoletoBancosRemessaAsync(BoletoTodos boleto, string Tipo, object userState) {
            if ((this.BoletoBancosRemessaOperationCompleted == null)) {
                this.BoletoBancosRemessaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBoletoBancosRemessaOperationCompleted);
            }
            this.InvokeAsync("BoletoBancosRemessa", new object[] {
                        boleto,
                        Tipo}, this.BoletoBancosRemessaOperationCompleted, userState);
        }
        
        private void OnBoletoBancosRemessaOperationCompleted(object arg) {
            if ((this.BoletoBancosRemessaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BoletoBancosRemessaCompleted(this, new BoletoBancosRemessaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BoletoCaixa", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] BoletoCaixa(BoletoCaixa boleto) {
            object[] results = this.Invoke("BoletoCaixa", new object[] {
                        boleto});
            return ((byte[])(results[0]));
        }
        
        /// <remarks/>
        public void BoletoCaixaAsync(BoletoCaixa boleto) {
            this.BoletoCaixaAsync(boleto, null);
        }
        
        /// <remarks/>
        public void BoletoCaixaAsync(BoletoCaixa boleto, object userState) {
            if ((this.BoletoCaixaOperationCompleted == null)) {
                this.BoletoCaixaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBoletoCaixaOperationCompleted);
            }
            this.InvokeAsync("BoletoCaixa", new object[] {
                        boleto}, this.BoletoCaixaOperationCompleted, userState);
        }
        
        private void OnBoletoCaixaOperationCompleted(object arg) {
            if ((this.BoletoCaixaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BoletoCaixaCompleted(this, new BoletoCaixaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BoletoBradesco {
        
        private string vencimentoField;
        
        private string valor_boletoField;
        
        private string cedente_nossoNumeroBoletoField;
        
        private string numeroDocumentoField;
        
        private string cedente_codigoField;
        
        private string cedente_cpfCnpjField;
        
        private string cedente_nomeField;
        
        private string cedente_agenciaField;
        
        private string cedente_contaField;
        
        private string cedente_digitoContaField;
        
        private string sacado_cpfCnpjField;
        
        private string sacado_nomeField;
        
        private string sacado_enderecoField;
        
        private string sacado_bairroField;
        
        private string sacado_cidadeField;
        
        private string sacado_cepField;
        
        private string sacado_ufField;
        
        private string carteiraField;
        
        /// <remarks/>
        public string vencimento {
            get {
                return this.vencimentoField;
            }
            set {
                this.vencimentoField = value;
            }
        }
        
        /// <remarks/>
        public string valor_boleto {
            get {
                return this.valor_boletoField;
            }
            set {
                this.valor_boletoField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_nossoNumeroBoleto {
            get {
                return this.cedente_nossoNumeroBoletoField;
            }
            set {
                this.cedente_nossoNumeroBoletoField = value;
            }
        }
        
        /// <remarks/>
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_codigo {
            get {
                return this.cedente_codigoField;
            }
            set {
                this.cedente_codigoField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_cpfCnpj {
            get {
                return this.cedente_cpfCnpjField;
            }
            set {
                this.cedente_cpfCnpjField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_nome {
            get {
                return this.cedente_nomeField;
            }
            set {
                this.cedente_nomeField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_agencia {
            get {
                return this.cedente_agenciaField;
            }
            set {
                this.cedente_agenciaField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_conta {
            get {
                return this.cedente_contaField;
            }
            set {
                this.cedente_contaField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_digitoConta {
            get {
                return this.cedente_digitoContaField;
            }
            set {
                this.cedente_digitoContaField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_cpfCnpj {
            get {
                return this.sacado_cpfCnpjField;
            }
            set {
                this.sacado_cpfCnpjField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_nome {
            get {
                return this.sacado_nomeField;
            }
            set {
                this.sacado_nomeField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_endereco {
            get {
                return this.sacado_enderecoField;
            }
            set {
                this.sacado_enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_bairro {
            get {
                return this.sacado_bairroField;
            }
            set {
                this.sacado_bairroField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_cidade {
            get {
                return this.sacado_cidadeField;
            }
            set {
                this.sacado_cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_cep {
            get {
                return this.sacado_cepField;
            }
            set {
                this.sacado_cepField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_uf {
            get {
                return this.sacado_ufField;
            }
            set {
                this.sacado_ufField = value;
            }
        }
        
        /// <remarks/>
        public string carteira {
            get {
                return this.carteiraField;
            }
            set {
                this.carteiraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BoletoCaixa {
        
        private string vencimentoField;
        
        private string valor_boletoField;
        
        private string cedente_nossoNumeroBoletoField;
        
        private string numeroDocumentoField;
        
        private string cedente_codigoField;
        
        private string cedente_cpfCnpjField;
        
        private string cedente_nomeField;
        
        private string cedente_agenciaField;
        
        private string cedente_contaField;
        
        private string cedente_digitoContaField;
        
        private string sacado_cpfCnpjField;
        
        private string sacado_nomeField;
        
        private string sacado_enderecoField;
        
        private string sacado_bairroField;
        
        private string sacado_cidadeField;
        
        private string sacado_cepField;
        
        private string sacado_ufField;
        
        /// <remarks/>
        public string vencimento {
            get {
                return this.vencimentoField;
            }
            set {
                this.vencimentoField = value;
            }
        }
        
        /// <remarks/>
        public string valor_boleto {
            get {
                return this.valor_boletoField;
            }
            set {
                this.valor_boletoField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_nossoNumeroBoleto {
            get {
                return this.cedente_nossoNumeroBoletoField;
            }
            set {
                this.cedente_nossoNumeroBoletoField = value;
            }
        }
        
        /// <remarks/>
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_codigo {
            get {
                return this.cedente_codigoField;
            }
            set {
                this.cedente_codigoField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_cpfCnpj {
            get {
                return this.cedente_cpfCnpjField;
            }
            set {
                this.cedente_cpfCnpjField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_nome {
            get {
                return this.cedente_nomeField;
            }
            set {
                this.cedente_nomeField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_agencia {
            get {
                return this.cedente_agenciaField;
            }
            set {
                this.cedente_agenciaField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_conta {
            get {
                return this.cedente_contaField;
            }
            set {
                this.cedente_contaField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_digitoConta {
            get {
                return this.cedente_digitoContaField;
            }
            set {
                this.cedente_digitoContaField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_cpfCnpj {
            get {
                return this.sacado_cpfCnpjField;
            }
            set {
                this.sacado_cpfCnpjField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_nome {
            get {
                return this.sacado_nomeField;
            }
            set {
                this.sacado_nomeField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_endereco {
            get {
                return this.sacado_enderecoField;
            }
            set {
                this.sacado_enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_bairro {
            get {
                return this.sacado_bairroField;
            }
            set {
                this.sacado_bairroField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_cidade {
            get {
                return this.sacado_cidadeField;
            }
            set {
                this.sacado_cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_cep {
            get {
                return this.sacado_cepField;
            }
            set {
                this.sacado_cepField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_uf {
            get {
                return this.sacado_ufField;
            }
            set {
                this.sacado_ufField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BoletoConcessionaria {
        
        private string identificacaoField;
        
        private string segmentoField;
        
        private string moedaField;
        
        private string valorField;
        
        private string empresa_orgaoField;
        
        private string nosso_numeroField;
        
        private string desc_servicoField;
        
        private BoletoTodos dadosField;
        
        /// <remarks/>
        public string identificacao {
            get {
                return this.identificacaoField;
            }
            set {
                this.identificacaoField = value;
            }
        }
        
        /// <remarks/>
        public string segmento {
            get {
                return this.segmentoField;
            }
            set {
                this.segmentoField = value;
            }
        }
        
        /// <remarks/>
        public string moeda {
            get {
                return this.moedaField;
            }
            set {
                this.moedaField = value;
            }
        }
        
        /// <remarks/>
        public string valor {
            get {
                return this.valorField;
            }
            set {
                this.valorField = value;
            }
        }
        
        /// <remarks/>
        public string empresa_orgao {
            get {
                return this.empresa_orgaoField;
            }
            set {
                this.empresa_orgaoField = value;
            }
        }
        
        /// <remarks/>
        public string nosso_numero {
            get {
                return this.nosso_numeroField;
            }
            set {
                this.nosso_numeroField = value;
            }
        }
        
        /// <remarks/>
        public string desc_servico {
            get {
                return this.desc_servicoField;
            }
            set {
                this.desc_servicoField = value;
            }
        }
        
        /// <remarks/>
        public BoletoTodos dados {
            get {
                return this.dadosField;
            }
            set {
                this.dadosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BoletoTodos {
        
        private string id_loteField;
        
        private string vencimentoField;
        
        private string valor_boletoField;
        
        private string cedente_nossoNumeroBoletoField;
        
        private string numeroDocumentoField;
        
        private string cedente_codigoField;
        
        private string cedente_cpfCnpjField;
        
        private string cedente_nomeField;
        
        private string cedente_agenciaField;
        
        private string cedente_contaField;
        
        private string cedente_digitoContaField;
        
        private string sacado_cpfCnpjField;
        
        private string sacado_nomeField;
        
        private string sacado_enderecoField;
        
        private string sacado_bairroField;
        
        private string sacado_cidadeField;
        
        private string sacado_cepField;
        
        private string sacado_ufField;
        
        private string carteiraField;
        
        private string bancoField;
        
        private string convenioField;
        
        private string instrucoesField;
        
        private LeilaoLotes lotesField;
        
        /// <remarks/>
        public string id_lote {
            get {
                return this.id_loteField;
            }
            set {
                this.id_loteField = value;
            }
        }
        
        /// <remarks/>
        public string vencimento {
            get {
                return this.vencimentoField;
            }
            set {
                this.vencimentoField = value;
            }
        }
        
        /// <remarks/>
        public string valor_boleto {
            get {
                return this.valor_boletoField;
            }
            set {
                this.valor_boletoField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_nossoNumeroBoleto {
            get {
                return this.cedente_nossoNumeroBoletoField;
            }
            set {
                this.cedente_nossoNumeroBoletoField = value;
            }
        }
        
        /// <remarks/>
        public string numeroDocumento {
            get {
                return this.numeroDocumentoField;
            }
            set {
                this.numeroDocumentoField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_codigo {
            get {
                return this.cedente_codigoField;
            }
            set {
                this.cedente_codigoField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_cpfCnpj {
            get {
                return this.cedente_cpfCnpjField;
            }
            set {
                this.cedente_cpfCnpjField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_nome {
            get {
                return this.cedente_nomeField;
            }
            set {
                this.cedente_nomeField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_agencia {
            get {
                return this.cedente_agenciaField;
            }
            set {
                this.cedente_agenciaField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_conta {
            get {
                return this.cedente_contaField;
            }
            set {
                this.cedente_contaField = value;
            }
        }
        
        /// <remarks/>
        public string cedente_digitoConta {
            get {
                return this.cedente_digitoContaField;
            }
            set {
                this.cedente_digitoContaField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_cpfCnpj {
            get {
                return this.sacado_cpfCnpjField;
            }
            set {
                this.sacado_cpfCnpjField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_nome {
            get {
                return this.sacado_nomeField;
            }
            set {
                this.sacado_nomeField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_endereco {
            get {
                return this.sacado_enderecoField;
            }
            set {
                this.sacado_enderecoField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_bairro {
            get {
                return this.sacado_bairroField;
            }
            set {
                this.sacado_bairroField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_cidade {
            get {
                return this.sacado_cidadeField;
            }
            set {
                this.sacado_cidadeField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_cep {
            get {
                return this.sacado_cepField;
            }
            set {
                this.sacado_cepField = value;
            }
        }
        
        /// <remarks/>
        public string sacado_uf {
            get {
                return this.sacado_ufField;
            }
            set {
                this.sacado_ufField = value;
            }
        }
        
        /// <remarks/>
        public string carteira {
            get {
                return this.carteiraField;
            }
            set {
                this.carteiraField = value;
            }
        }
        
        /// <remarks/>
        public string banco {
            get {
                return this.bancoField;
            }
            set {
                this.bancoField = value;
            }
        }
        
        /// <remarks/>
        public string convenio {
            get {
                return this.convenioField;
            }
            set {
                this.convenioField = value;
            }
        }
        
        /// <remarks/>
        public string instrucoes {
            get {
                return this.instrucoesField;
            }
            set {
                this.instrucoesField = value;
            }
        }
        
        /// <remarks/>
        public LeilaoLotes lotes {
            get {
                return this.lotesField;
            }
            set {
                this.lotesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LeilaoLotes {
        
        private string leilaoField;
        
        private string[] lotesField;
        
        /// <remarks/>
        public string leilao {
            get {
                return this.leilaoField;
            }
            set {
                this.leilaoField = value;
            }
        }
        
        /// <remarks/>
        public string[] lotes {
            get {
                return this.lotesField;
            }
            set {
                this.lotesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void BoletoBradescoCompletedEventHandler(object sender, BoletoBradescoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoletoBradescoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BoletoBradescoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void BoletoBancosCompletedEventHandler(object sender, BoletoBancosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoletoBancosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BoletoBancosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void BoletoBancosRetornoLinhaCompletedEventHandler(object sender, BoletoBancosRetornoLinhaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoletoBancosRetornoLinhaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BoletoBancosRetornoLinhaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string linha {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public int linha_id {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void FaturaConcessionariaCompletedEventHandler(object sender, FaturaConcessionariaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FaturaConcessionariaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FaturaConcessionariaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void BoletoBancosRemessaCompletedEventHandler(object sender, BoletoBancosRemessaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoletoBancosRemessaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BoletoBancosRemessaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string remessa_retorno {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void BoletoCaixaCompletedEventHandler(object sender, BoletoCaixaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BoletoCaixaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BoletoCaixaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591