//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobLink.WSSap.Repositorio.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://srvsappidev:50100/XISOAPAdapter/MessageServlet?senderParty=&senderService=" +
            "LINKPATIOS_2_QAD&receiverParty=&receiverService=&interface=si_cliente_request&in" +
            "terfaceNamespace=http%3A%2F%2Fwww.l2r.com.br%2Fpi%2Fclientes")]
        public string MobLink_WSSap_Repositorio_si_cliente_requestService_si_cliente_requestService {
            get {
                return ((string)(this["MobLink_WSSap_Repositorio_si_cliente_requestService_si_cliente_requestService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://srvsappidev:50100/XISOAPAdapter/MessageServlet?senderParty=&senderService=" +
            "LINKPATIOS_2_QAD&receiverParty=&receiverService=&interface=si_modificacao_parcei" +
            "ro&interfaceNamespace=http%3A%2F%2Fwww.l2r.com.br%2Fpi%2Fmodificacao_parceiro")]
        public string MobLink_WSSap_Repositorio_si_modificacao_parceiroService_si_modificacao_parceiroService {
            get {
                return ((string)(this["MobLink_WSSap_Repositorio_si_modificacao_parceiroService_si_modificacao_parceiroS" +
                    "ervice"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://srvsappiprd:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=" +
            "LINKPATIOS&receiverParty=&receiverService=&interface=si_ordemvenda_request&inter" +
            "faceNamespace=http%3A%2F%2Fwww.l2r.com.br%2Fpi%2Fordemvenda")]
        public string MobLink_WSSap_Repositorio_si_ordemvenda_requestService_si_ordemvenda_requestService {
            get {
                return ((string)(this["MobLink_WSSap_Repositorio_si_ordemvenda_requestService_si_ordemvenda_requestServi" +
                    "ce"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://srvsappidev:50100/XISOAPAdapter/MessageServlet?senderParty=&senderService=" +
            "LINKPATIOS_2_QAD&receiverParty=&receiverService=&interface=si_ordem_interna_requ" +
            "est&interfaceNamespace=http%3A%2F%2Fwww.l2r.com.br%2Fpi%2Ftitulo_ordem_interna")]
        public string MobLink_WSSap_Repositorio_si_ordem_interna_requestService_si_ordem_interna_requestService {
            get {
                return ((string)(this["MobLink_WSSap_Repositorio_si_ordem_interna_requestService_si_ordem_interna_reques" +
                    "tService"]));
            }
        }
    }
}
