//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MobLink.WSSap.Repositorio.si_cliente_requestService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="si_cliente_requestBinding", Namespace="http://www.l2r.com.br/pi/clientes")]
    public partial class si_cliente_requestService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback si_cliente_requestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public si_cliente_requestService() {
            this.Url = global::MobLink.WSSap.Repositorio.Properties.Settings.Default.MobLink_WSSap_Repositorio_si_cliente_requestService_si_cliente_requestService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event si_cliente_requestCompletedEventHandler si_cliente_requestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void si_cliente_request([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.l2r.com.br/pi/clientes")] dt_cliente_request mt_cliente_request) {
            this.Invoke("si_cliente_request", new object[] {
                        mt_cliente_request});
        }
        
        /// <remarks/>
        public void si_cliente_requestAsync(dt_cliente_request mt_cliente_request) {
            this.si_cliente_requestAsync(mt_cliente_request, null);
        }
        
        /// <remarks/>
        public void si_cliente_requestAsync(dt_cliente_request mt_cliente_request, object userState) {
            if ((this.si_cliente_requestOperationCompleted == null)) {
                this.si_cliente_requestOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_cliente_requestOperationCompleted);
            }
            this.InvokeAsync("si_cliente_request", new object[] {
                        mt_cliente_request}, this.si_cliente_requestOperationCompleted, userState);
        }
        
        private void Onsi_cliente_requestOperationCompleted(object arg) {
            if ((this.si_cliente_requestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_cliente_requestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.l2r.com.br/pi/clientes")]
    public partial class dt_cliente_request {
        
        private string iDTRANSACAOField;
        
        private string bUKRSField;
        
        private string vKORGField;
        
        private string nAME1Field;
        
        private string sTRASField;
        
        private string hOUSE_NUM1Field;
        
        private string bUILDINGField;
        
        private string fLOORField;
        
        private string oRT02Field;
        
        private string pSTLZField;
        
        private string mCOD3Field;
        
        private string rEGIOField;
        
        private string lAND1Field;
        
        private string tELF1Field;
        
        private string sMTP_ADDRField;
        
        private string sTCD1Field;
        
        private string sTCD2Field;
        
        private string sTCD3Field;
        
        private string sTCD4Field;
        
        private string zWELSField;
        
        private string zTERMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string IDTRANSACAO {
            get {
                return this.iDTRANSACAOField;
            }
            set {
                this.iDTRANSACAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUKRS {
            get {
                return this.bUKRSField;
            }
            set {
                this.bUKRSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VKORG {
            get {
                return this.vKORGField;
            }
            set {
                this.vKORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NAME1 {
            get {
                return this.nAME1Field;
            }
            set {
                this.nAME1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRAS {
            get {
                return this.sTRASField;
            }
            set {
                this.sTRASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOUSE_NUM1 {
            get {
                return this.hOUSE_NUM1Field;
            }
            set {
                this.hOUSE_NUM1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUILDING {
            get {
                return this.bUILDINGField;
            }
            set {
                this.bUILDINGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FLOOR {
            get {
                return this.fLOORField;
            }
            set {
                this.fLOORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORT02 {
            get {
                return this.oRT02Field;
            }
            set {
                this.oRT02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PSTLZ {
            get {
                return this.pSTLZField;
            }
            set {
                this.pSTLZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MCOD3 {
            get {
                return this.mCOD3Field;
            }
            set {
                this.mCOD3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REGIO {
            get {
                return this.rEGIOField;
            }
            set {
                this.rEGIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string LAND1 {
            get {
                return this.lAND1Field;
            }
            set {
                this.lAND1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELF1 {
            get {
                return this.tELF1Field;
            }
            set {
                this.tELF1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SMTP_ADDR {
            get {
                return this.sMTP_ADDRField;
            }
            set {
                this.sMTP_ADDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STCD1 {
            get {
                return this.sTCD1Field;
            }
            set {
                this.sTCD1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STCD2 {
            get {
                return this.sTCD2Field;
            }
            set {
                this.sTCD2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STCD3 {
            get {
                return this.sTCD3Field;
            }
            set {
                this.sTCD3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STCD4 {
            get {
                return this.sTCD4Field;
            }
            set {
                this.sTCD4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZWELS {
            get {
                return this.zWELSField;
            }
            set {
                this.zWELSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTERM {
            get {
                return this.zTERMField;
            }
            set {
                this.zTERMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void si_cliente_requestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591