//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MobLink.WSSap.Repositorio.si_modificacao_parceiroService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="si_modificacao_parceiroBinding", Namespace="http://www.l2r.com.br/pi/modificacao_parceiro")]
    public partial class si_modificacao_parceiroService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback si_modificacao_parceiroOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public si_modificacao_parceiroService() {
            this.Url = global::MobLink.WSSap.Repositorio.Properties.Settings.Default.MobLink_WSSap_Repositorio_si_modificacao_parceiroService_si_modificacao_parceiroService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event si_modificacao_parceiroCompletedEventHandler si_modificacao_parceiroCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void si_modificacao_parceiro([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.l2r.com.br/pi/modificacao_parceiro")] dt_modificacao_parceiro mt_modicacao_parceiro) {
            this.Invoke("si_modificacao_parceiro", new object[] {
                        mt_modicacao_parceiro});
        }
        
        /// <remarks/>
        public void si_modificacao_parceiroAsync(dt_modificacao_parceiro mt_modicacao_parceiro) {
            this.si_modificacao_parceiroAsync(mt_modicacao_parceiro, null);
        }
        
        /// <remarks/>
        public void si_modificacao_parceiroAsync(dt_modificacao_parceiro mt_modicacao_parceiro, object userState) {
            if ((this.si_modificacao_parceiroOperationCompleted == null)) {
                this.si_modificacao_parceiroOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_modificacao_parceiroOperationCompleted);
            }
            this.InvokeAsync("si_modificacao_parceiro", new object[] {
                        mt_modicacao_parceiro}, this.si_modificacao_parceiroOperationCompleted, userState);
        }
        
        private void Onsi_modificacao_parceiroOperationCompleted(object arg) {
            if ((this.si_modificacao_parceiroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_modificacao_parceiroCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.l2r.com.br/pi/modificacao_parceiro")]
    public partial class dt_modificacao_parceiro {
        
        private string iDTRANSACAOField;
        
        private string tIPO_PARCEIROField;
        
        private string cOD_PARCEIROField;
        
        private string cOD_ORGField;
        
        private string sTRASField;
        
        private string hOUSE_NUM1Field;
        
        private string bUILDINGField;
        
        private string fLOORField;
        
        private string oRT02Field;
        
        private string pSTLZField;
        
        private string mCOD3Field;
        
        private string rEGIOField;
        
        private string tELF1Field;
        
        private string sMTP_ADDRField;
        
        private string zTERMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string IDTRANSACAO {
            get {
                return this.iDTRANSACAOField;
            }
            set {
                this.iDTRANSACAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TIPO_PARCEIRO {
            get {
                return this.tIPO_PARCEIROField;
            }
            set {
                this.tIPO_PARCEIROField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_PARCEIRO {
            get {
                return this.cOD_PARCEIROField;
            }
            set {
                this.cOD_PARCEIROField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string COD_ORG {
            get {
                return this.cOD_ORGField;
            }
            set {
                this.cOD_ORGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string STRAS {
            get {
                return this.sTRASField;
            }
            set {
                this.sTRASField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string HOUSE_NUM1 {
            get {
                return this.hOUSE_NUM1Field;
            }
            set {
                this.hOUSE_NUM1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BUILDING {
            get {
                return this.bUILDINGField;
            }
            set {
                this.bUILDINGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FLOOR {
            get {
                return this.fLOORField;
            }
            set {
                this.fLOORField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORT02 {
            get {
                return this.oRT02Field;
            }
            set {
                this.oRT02Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PSTLZ {
            get {
                return this.pSTLZField;
            }
            set {
                this.pSTLZField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MCOD3 {
            get {
                return this.mCOD3Field;
            }
            set {
                this.mCOD3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string REGIO {
            get {
                return this.rEGIOField;
            }
            set {
                this.rEGIOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TELF1 {
            get {
                return this.tELF1Field;
            }
            set {
                this.tELF1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SMTP_ADDR {
            get {
                return this.sMTP_ADDRField;
            }
            set {
                this.sMTP_ADDRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTERM {
            get {
                return this.zTERMField;
            }
            set {
                this.zTERMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void si_modificacao_parceiroCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591