//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Este código-fonte foi gerado automaticamente por Microsoft.VSDesigner, Versão 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace MobLink.WSSap.Repositorio.si_ordemvenda_requestService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="si_ordemvenda_requestBinding", Namespace="http://www.l2r.com.br/pi/ordemvenda")]
    public partial class si_ordemvenda_requestService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback si_ordemvenda_requestOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public si_ordemvenda_requestService() {
            this.Url = global::MobLink.WSSap.Repositorio.Properties.Settings.Default.MobLink_WSSap_Repositorio_si_ordemvenda_requestService_si_ordemvenda_requestService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event si_ordemvenda_requestCompletedEventHandler si_ordemvenda_requestCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://sap.com/xi/WebService/soap1.1", OneWay=true, Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        public void si_ordemvenda_request([System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.l2r.com.br/pi/ordemvenda")] dt_ordemvenda_request mt_ordemvenda_request) {
            this.Invoke("si_ordemvenda_request", new object[] {
                        mt_ordemvenda_request});
        }
        
        /// <remarks/>
        public void si_ordemvenda_requestAsync(dt_ordemvenda_request mt_ordemvenda_request) {
            this.si_ordemvenda_requestAsync(mt_ordemvenda_request, null);
        }
        
        /// <remarks/>
        public void si_ordemvenda_requestAsync(dt_ordemvenda_request mt_ordemvenda_request, object userState) {
            if ((this.si_ordemvenda_requestOperationCompleted == null)) {
                this.si_ordemvenda_requestOperationCompleted = new System.Threading.SendOrPostCallback(this.Onsi_ordemvenda_requestOperationCompleted);
            }
            this.InvokeAsync("si_ordemvenda_request", new object[] {
                        mt_ordemvenda_request}, this.si_ordemvenda_requestOperationCompleted, userState);
        }
        
        private void Onsi_ordemvenda_requestOperationCompleted(object arg) {
            if ((this.si_ordemvenda_requestCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.si_ordemvenda_requestCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.l2r.com.br/pi/ordemvenda")]
    public partial class dt_ordemvenda_request {
        
        private string iDTRANSACAOField;
        
        private string aUARTField;
        
        private string wERKSField;
        
        private string vBELNField;
        
        private string fKDATField;
        
        private string kUNNRField;
        
        private string bSTNKField;
        
        private string oRDER_TXTField;
        
        private string zZPROCField;
        
        private string zZPERIField;
        
        private string zZLEILField;
        
        private string zTERMField;
        
        private dt_ordemvenda_requestITEMS[] iTEMSField;
        
        private dt_ordemvenda_requestDOC_PAGAM[] dOC_PAGAMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="integer")]
        public string IDTRANSACAO {
            get {
                return this.iDTRANSACAOField;
            }
            set {
                this.iDTRANSACAOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AUART {
            get {
                return this.aUARTField;
            }
            set {
                this.aUARTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string WERKS {
            get {
                return this.wERKSField;
            }
            set {
                this.wERKSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string VBELN {
            get {
                return this.vBELNField;
            }
            set {
                this.vBELNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string FKDAT {
            get {
                return this.fKDATField;
            }
            set {
                this.fKDATField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string KUNNR {
            get {
                return this.kUNNRField;
            }
            set {
                this.kUNNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string BSTNK {
            get {
                return this.bSTNKField;
            }
            set {
                this.bSTNKField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ORDER_TXT {
            get {
                return this.oRDER_TXTField;
            }
            set {
                this.oRDER_TXTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZPROC {
            get {
                return this.zZPROCField;
            }
            set {
                this.zZPROCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZPERI {
            get {
                return this.zZPERIField;
            }
            set {
                this.zZPERIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZZLEIL {
            get {
                return this.zZLEILField;
            }
            set {
                this.zZLEILField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ZTERM {
            get {
                return this.zTERMField;
            }
            set {
                this.zTERMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ITEMS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_ordemvenda_requestITEMS[] ITEMS {
            get {
                return this.iTEMSField;
            }
            set {
                this.iTEMSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DOC_PAGAM", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public dt_ordemvenda_requestDOC_PAGAM[] DOC_PAGAM {
            get {
                return this.dOC_PAGAMField;
            }
            set {
                this.dOC_PAGAMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.l2r.com.br/pi/ordemvenda")]
    public partial class dt_ordemvenda_requestITEMS {
        
        private string mATNRField;
        
        private decimal mENGEField;
        
        private decimal kBETRField;
        
        private decimal kBRTR_DESCField;
        
        private bool kBRTR_DESCFieldSpecified;
        
        private string aUFNRField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MATNR {
            get {
                return this.mATNRField;
            }
            set {
                this.mATNRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal MENGE {
            get {
                return this.mENGEField;
            }
            set {
                this.mENGEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal KBETR {
            get {
                return this.kBETRField;
            }
            set {
                this.kBETRField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal KBRTR_DESC {
            get {
                return this.kBRTR_DESCField;
            }
            set {
                this.kBRTR_DESCField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KBRTR_DESCSpecified {
            get {
                return this.kBRTR_DESCFieldSpecified;
            }
            set {
                this.kBRTR_DESCFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AUFNR {
            get {
                return this.aUFNRField;
            }
            set {
                this.aUFNRField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.l2r.com.br/pi/ordemvenda")]
    public partial class dt_ordemvenda_requestDOC_PAGAM {
        
        private string mEIO_PAGField;
        
        private string dOCUMENTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MEIO_PAG {
            get {
                return this.mEIO_PAGField;
            }
            set {
                this.mEIO_PAGField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DOCUMENTO {
            get {
                return this.dOCUMENTOField;
            }
            set {
                this.dOCUMENTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2046.0")]
    public delegate void si_ordemvenda_requestCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591